Repository LIS/LISAv2, pull requests merged in 2018-12, with the labels that each got.

#483 Azure: fix modinfo error
  Testscripts/Linux/CORE-LogCollector.sh
Labels: bug, enhancement

#485 ReorgTest Cases
  XML/TestCases/FunctionalTests-DynamicMemory.xml
  XML/TestCases/FunctionalTests-LiveMigration.xml
  XML/TestCases/FunctionalTests-Network.xml
  XML/TestCases/FunctionalTests-Storage.xml
  XML/TestCases/FunctionalTests-VSSBackup.xml
  XML/TestCases/FunctionalTests.xml
Labels: enhancement

#477 Support run test case against SASURL and update report format.
  AutomationManager.ps1
  Libraries/Azure.psm1
  Libraries/LISAV2-Framework.psm1
  Libraries/LogProcessing.psm1
  Libraries/XmlProcessing.psm1
  Utilities/CheckImageUpdate.ps1
Labels: enhancement

#491 perf_framework: iperf3: output perf results in a generic way
  Testscripts/Windows/PERF-NETWORK-TCP-SINGLE-CONNECTION-THROUGHPUT.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/PerformanceTests.xml
Labels: New Feature, enhancement

#487 Remove enable root for each case.
  Libraries/LISAV2-Framework.psm1
Labels: enhancement

#496 Improve testing condition for DPDK
  Testscripts/Windows/DPDK-TESTCASE-DRIVER.ps1
  Testscripts/Windows/dpdk-testFWD.ps1
  Testscripts/Windows/dpdk-testFailsafe.ps1
  Testscripts/Windows/dpdk-testPMD.ps1
Labels: P1, enhancement

#502 stor_perf: fix backwards compatibility in params
  Testscripts/Linux/perf_fio.sh
Labels: bug

#501 Fix transient azure api failures and parameterize ntttcp connections
  Libraries/Azure.psm1
  Testscripts/Linux/perf_ntttcp.sh
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/PerformanceTests.xml
Labels: bug, enhancement

#500 perf_stor: Storage 4K-IO/1024K-IO params update and refactor
  Libraries/HyperV.psm1
  Testscripts/Linux/perf_fio.sh
  Testscripts/Windows/AddHardDisk.ps1
  Testscripts/Windows/PERF-STORAGE-MULTIDISK-RAID0-FIO.ps1
  XML/AzureVMSizeToHyperVMapping.xml
  XML/TestCases/PerformanceTests.xml
Labels: CodeRefactoring, enhancement

#508 perf_ntttcp: perf_stor: implement perf result comparison framework
  Testscripts/Windows/PERF-NETWORK-TCP-SINGLE-CONNECTION-THROUGHPUT.ps1
  Testscripts/Windows/PERF-NETWORK-THROUGHPUT-MULTICONNECTION-NTTTCP.ps1
  Testscripts/Windows/PERF-STORAGE-MULTIDISK-RAID0-FIO.ps1
Labels: CodeRefactoring, enhancement

#506 Add VmOfToday utility
  Utilities/VmOfToday.ps1
Labels: Utility

#505 DPDK run-time can not refresh Global variable for distro name
  Libraries/CommonFunctions.psm1
  Testscripts/Linux/dpdkSetupAndRunTest.sh
  Testscripts/Linux/dpdkUtils.sh
  Testscripts/Windows/DPDK-TESTCASE-DRIVER.ps1
  Testscripts/Windows/VERIFY-DPDK-BUILD-AND-TESTPMD-TEST.ps1
  Testscripts/Windows/VERIFY-DPDK-COMPLIANCE.ps1
  Testscripts/Windows/VERIFY-SRIOV-FAILSAFE-FOR-DPDK.ps1
  XML/Other/testfwd_pps_lowerbound.xml
Labels: bug, enhancement

#518 LISAv2 code cleanup
  AutomationManager.ps1
  Libraries/Azure.psm1
  Libraries/LogProcessing.psm1
  Run-LisaV2.ps1
  Testscripts/Windows/BVT-VERIFY-DEPLOYMENT-PROVISION.ps1
  Testscripts/Windows/DPDK-TESTCASE-DRIVER.ps1
  Testscripts/Windows/NESTED-HYPERV-NTTTCP-DIFFERENT-L1-NAT.ps1
  Testscripts/Windows/NESTED-HYPERV-NTTTCP-DIFFERENT-L1-PUBLIC-BRIDGE.ps1
  Testscripts/Windows/NESTED-HYPERV-STORAGE-PERF.ps1
  Testscripts/Windows/NESTED-KVM-LAGSCOPE-DIFFERENT-L1-PUBLIC-BRIDGE.ps1
  Testscripts/Windows/NESTED-KVM-NETPERF-PPS.ps1
  Testscripts/Windows/NESTED-KVM-NTTTCP-DIFFERENT-L1-PUBLIC-BRIDGE.ps1
  Testscripts/Windows/NESTED-KVM-NTTTCP-PRIVATE-BRIDGE.ps1
  Testscripts/Windows/NESTED-KVM-STORAGE-PERF.ps1
  Testscripts/Windows/PERF-NETWORK-TCP-LATENCY-MULTICONNECTION-LAGSCOPE.ps1
  Testscripts/Windows/PERF-NETWORK-TCP-NETPERF.ps1
  Testscripts/Windows/PERF-NETWORK-THROUGHPUT-MULTICONNECTION-NTTTCP.ps1
  Testscripts/Windows/PERF-NETWORK-UDP-THROUGHPUT-MULTICONNECTION-IPERF3.ps1
  Testscripts/Windows/PERF-STORAGE-OVER-NFS.ps1
  Testscripts/Windows/PERF-SYSCALL-BENCHMARK.ps1
  Testscripts/Windows/STRESS-Web.ps1
  Testscripts/Windows/VERIFY-DISK-WITH-NOBARRIER.ps1
  Testscripts/Windows/VERIFY-ENABLE-DISABLE-SRIOV-ON-EXISTING-VM.ps1
  Testscripts/Windows/VERIFY-INFINIBAND-MultiVM.ps1
  Testscripts/Windows/VERIFY-NVIDIA-CUDA-DRIVER-INSTALLATION.ps1
  Testscripts/Windows/VERIFY-SRIOV-FAILSAFE-FOR-DPDK.ps1
  XML/TestParameters.xml
Labels: enhancement

#520 Update subscription usage report URL.
  Utilities/Get-SubscriptionUsage.ps1
Labels: enhancement

#522 lisav2: fix azure secrets load
  Run-LisaV2.ps1
Labels: LISAv2 Broken, P0

#532 Remove unnecessary global variables
  AutomationManager.ps1
  Libraries/Azure.psm1
  Libraries/CommonFunctions.psm1
  Testscripts/Windows/BVT-VERIFY-DISKSIZE.ps1
  Testscripts/Windows/BVT-VERIFY-SSHD-CONFIG.ps1
  Testscripts/Windows/BVT-VERIFY-VHD-PREREQUISITES.ps1
Labels: enhancement

#517 Fix CORE-LogCollector.sh for multiple distros
  Testscripts/Linux/CORE-LogCollector.sh
Labels: bug

#538 CAPTURE-VHD-BEFORE-TEST.ps1: small fixes and code cleanup
  Testscripts/Windows/CAPTURE-VHD-BEFORE-TEST.ps1
Labels: enhancement

#534 Fix issue when run case BVT-VERIFY-KVP-DAEMON-STATUS found in upstream pipeline
  Testscripts/Windows/BVT-VERIFY-KVP-DAEMON-STATUS.ps1
Labels: enhancement

#527 Change the test deployment ID format
  Libraries/Azure.psm1
  Libraries/TestHelpers.psm1
  Run-LisaV2.ps1
Labels: CodeRefactoring

#537 perf_fio: squash database results by qdepth
  Testscripts/Windows/PERF-STORAGE-MULTIDISK-RAID0-FIO.ps1
Labels: bug

#535 Update name of setupType for one VM
  XML/TestCases/BVT.xml
  XML/TestCases/CommunityTests.xml
  XML/TestCases/FunctionalTests-DPDK.xml
  XML/TestCases/FunctionalTests-DynamicMemory.xml
  XML/TestCases/FunctionalTests-GPU.xml
  XML/TestCases/FunctionalTests-KVP.xml
  XML/TestCases/FunctionalTests-LiveMigration.xml
  XML/TestCases/FunctionalTests-Network.xml
  XML/TestCases/FunctionalTests-SRIOV.xml
  XML/TestCases/FunctionalTests-Storage.xml
  XML/TestCases/FunctionalTests-VSSBackup.xml
  XML/TestCases/FunctionalTests-WALA.xml
  XML/TestCases/FunctionalTests.xml
  XML/TestCases/NestedVmTests.xml
  XML/TestCases/Other.xml
  XML/TestCases/PerformanceTests.xml
  XML/TestCases/StressTests.xml
  XML/VMConfigurations/CommunityTestsConfigurations.xml
  XML/VMConfigurations/FunctionalTestsConfigurations.xml
  XML/VMConfigurations/NestedVmTestsConfigurations.xml
  XML/VMConfigurations/PerformanceTestsConfigurations.xml
  XML/VMConfigurations/SmokeTestsConfigurations.xml
  XML/VMConfigurations/StressTestsConfigurations.xml
Labels: enhancement

#541 Add display powerstate of VM for Get-AzureVMs.ps1
  Utilities/Get-AzureVMs.ps1
Labels: enhancement

#543 Fix issue that Provisioning.UseCloudInit is not set to n, and other two typos
  Testscripts/Windows/CAPTURE-VHD-BEFORE-TEST.ps1
  Testscripts/Windows/NESTED-HYPERV-STORAGE-PERF.ps1
  Testscripts/Windows/PERF-SYSCALL-BENCHMARK.ps1
Labels: bug

#545 Update names of setupType for multiple VMs, remove unused S1C15
  XML/TestCases/FunctionalTests-DPDK.xml
  XML/TestCases/FunctionalTests-DynamicMemory.xml
  XML/TestCases/FunctionalTests-InfiniBand.xml
  XML/TestCases/PerformanceTests-DPDK.xml
  XML/VMConfigurations/FunctionalTestsConfigurations.xml
  XML/VMConfigurations/PerformanceTestsConfigurations.xml
Labels: enhancement

#549 Rename the log file to TestLogs.zip in groove file
  .gitignore
  JenkinsPipelines/Run-Boot-Stress-Tests.groovy
  JenkinsPipelines/Run-Linux-Tests.groovy
Labels: bug

#546 Part update for Shell Check
  Testscripts/Linux/BVT-CORE-RELOAD-MODULES.sh
  Testscripts/Linux/BVT-CORE-VERIFY-LIS-MODULES-VERSION.sh
  Testscripts/Linux/CORE-CPUVerifyOnline.sh
  Testscripts/Linux/CORE-ConfigTimeSync.sh
  Testscripts/Linux/CORE-InitrdModulesCheck.sh
  Testscripts/Linux/DM_HotAdd_Verify_udev.sh
  Testscripts/Linux/DetectLinuxDistro.sh
  Testscripts/Linux/KDUMP-Config.sh
  Testscripts/Linux/KDUMP-Execute.sh
  Testscripts/Linux/KDUMP-NFSconfig.sh
  Testscripts/Linux/KDUMP-Results.sh
  Testscripts/Linux/KVP-BasicChecks.sh
  Testscripts/Linux/LIS-Check-HypervDaemons-Files-Status.sh
  Testscripts/Linux/LIS-Mount-CD.sh
  Testscripts/Linux/LSVMBUS.sh
  Testscripts/Linux/Linux-Test-Project-Tests.sh
  Testscripts/Linux/NET-Operstate.sh
  Testscripts/Linux/NUMA_check.sh
  Testscripts/Linux/PC_Stop_VSS_Daemon.sh
  Testscripts/Linux/SR-IOV-Utils.sh
  Testscripts/Linux/SRIOV-DisableVF.sh
  Testscripts/Linux/SRIOV-Iperf-Stress.sh
  Testscripts/Linux/SRIOV-ModuleReload.sh
  Testscripts/Linux/SRIOV-Verify-lspci.sh
  Testscripts/Linux/SRIOV-VerifyVF-Connection.sh
  Testscripts/Linux/STORAGE-HotRemove.sh
  Testscripts/Linux/STORAGE-LargeDisk.sh
  Testscripts/Linux/check_triggered_nmi.sh
  Testscripts/Linux/dpdk-testFWD.sh
  Testscripts/Linux/dpdk-testFailsafe.sh
  Testscripts/Linux/dpdk-testPMD.sh
  Testscripts/Linux/dpdkSetup.sh
  Testscripts/Linux/dpdkSetupAndRunTest.sh
  Testscripts/Linux/dpdkTestPmd.sh
  Testscripts/Linux/enableRoot.sh
  Testscripts/Linux/nested_kvm_basic_test.sh
  Testscripts/Linux/nobarrier.sh
  Testscripts/Linux/perf_iperf3.sh
  Testscripts/Linux/perf_lagscope.sh
  Testscripts/Linux/perf_netperf.sh
  Testscripts/Linux/perf_ntttcp.sh
  Testscripts/Linux/perf_syscallbenchmark.sh
  Testscripts/Linux/perf_xfstesting.sh
  Testscripts/Linux/stress_web.sh
  Testscripts/Linux/verify_vmbus_interrupts.sh
Labels: enhancement

#533 lisav2: remove hardcoded root user for functional test cases
  Libraries/CommonFunctions.psm1
  Testscripts/Windows/BVT-VERIFY-KVP-DAEMON-STATUS.ps1
  Testscripts/Windows/DM-HOTADD-STRESS-APP.ps1
  Testscripts/Windows/FCOPY-DISABLE-ENABLE.ps1
  Testscripts/Windows/FCOPY-LARGE-FILE.ps1
  Testscripts/Windows/FCOPY-NEGATIVE.ps1
  Testscripts/Windows/FCOPY-REPEATED-DELETE.ps1
  Testscripts/Windows/Heartbeat-PausedCritical.ps1
  Testscripts/Windows/KDUMP-TestScript.ps1
  Testscripts/Windows/KVP-MaxRead.ps1
  Testscripts/Windows/KVP-PushKeyValues.ps1
  Testscripts/Windows/Max-vCPU.ps1
  Testscripts/Windows/SQM-Basic.ps1
  Testscripts/Windows/STORAGE-HotUnplug.ps1
  Testscripts/Windows/STRESS-MTU-Netvsc-Reload.ps1
  Testscripts/Windows/Timesync-VDSO.ps1
Labels: CodeRefactoring

#552 lisav2: allow multiple test categories, comma separated
  Libraries/LISAV2-Framework.psm1
Labels: enhancement

#551 Fix new zip file issue when run test with -EnableTelemetry.
  Libraries/CommonFunctions.psm1
  Run-LisaV2.ps1
  Utilities/UploadFilesToStorageAccount.ps1
Labels: bug

#553 Update the logic of UploadFilesToStorageAccount.ps1 for case of user provided key
  Run-LisaV2.ps1
  Utilities/UploadFilesToStorageAccount.ps1
Labels: bug

#554 'Update grub' put into a wrong place
  Testscripts/Linux/customKernelInstall.sh
Labels: bug

#550 NVMe Direct: Added 5 testcases for Azure and Hyper-V
  Testscripts/Linux/nvme_basic_validation.sh
  Testscripts/Linux/nvme_functional.sh
  Testscripts/Linux/nvme_functional_expected_fails.sh
  Testscripts/Linux/perf_fio.sh
  Testscripts/Windows/SETUP-Add-NVME-Disk.ps1
  Testscripts/Windows/SETUP-Remove-NVME-Disk.ps1
  XML/TestCases/FunctionalTests-NVME.xml
  XML/TestCases/PerformanceTests.xml
Labels: New Testcase

#557 Fix install msft-kernel issue
  Testscripts/Linux/customKernelInstall.sh
Labels: bug

#558 perf: fix nfs installation for rhel/centos/sles
  Testscripts/Linux/CreateRaid.sh
  Testscripts/Linux/perf_fio_nfs.sh
  Testscripts/Linux/utils.sh
Labels: enhancement

#548 lisav2: speed up kernel boot fail check
  Libraries/Azure.psm1
  Libraries/HyperV.psm1
  Libraries/LISAV2-Framework.psm1
  Testscripts/Windows/BVT-VERIFY-RESTART.ps1
  Testscripts/Windows/BVT-VERIFY-SHUTDOWN.ps1
  Testscripts/Windows/NESTED-HYPERV-NTTTCP-DIFFERENT-L1-NAT.ps1
  Testscripts/Windows/NESTED-HYPERV-NTTTCP-DIFFERENT-L1-PUBLIC-BRIDGE.ps1
  Testscripts/Windows/STRESSTEST-VERIFY-RESTART.ps1
  UnitTests/PowerShell/Libraries.Azure.Tests.ps1
  Utilities/VmOfToday.ps1
Labels: CodeRefactoring, enhancement

#561 [Part 1/2] Update setup type for 2 VMs
  Libraries/HyperV.psm1
  Testscripts/Windows/NESTED-HYPERV-NTTTCP-DIFFERENT-L1-NAT.ps1
  Testscripts/Windows/NESTED-HYPERV-NTTTCP-DIFFERENT-L1-PUBLIC-BRIDGE.ps1
  Testscripts/Windows/NESTED-KVM-LAGSCOPE-DIFFERENT-L1-PUBLIC-BRIDGE.ps1
  Testscripts/Windows/NESTED-KVM-NETPERF-PPS.ps1
  Testscripts/Windows/NESTED-KVM-NTTTCP-DIFFERENT-L1-PUBLIC-BRIDGE.ps1
  Testscripts/Windows/VERIFY-INFINIBAND-MultiVM.ps1
  XML/TestCases/FunctionalTests-DPDK.xml
  XML/TestCases/FunctionalTests-InfiniBand.xml
  XML/TestCases/FunctionalTests-SRIOV.xml
  XML/TestCases/NestedVmTests.xml
  XML/TestCases/PerformanceTests-DPDK.xml
  XML/TestCases/PerformanceTests.xml
  XML/VMConfigurations/CommunityTestsConfigurations.xml
  XML/VMConfigurations/FunctionalTestsConfigurations.xml
  XML/VMConfigurations/NestedVmTestsConfigurations.xml
  XML/VMConfigurations/PerformanceTestsConfigurations.xml
Labels: enhancement

#563 Fix for cloud-init issue
  Testscripts/Windows/CAPTURE-VHD-BEFORE-TEST.ps1
Labels: enhancement
