Repository LIS/LISAv2, pull requests merged in 2018-07, with the labels that each got.

#82 Added reboot azure stress test and fixed scripts
  RunTests.ps1
  Testscripts/Windows/STRESSTEST-VERIFY-RESTART.ps1
  Utilities/UpdateGlobalConfigurationFromXmlSecrets.ps1
  XML/TestCases/StressTests.xml
Labels: New Testcase

#78 Major - Added support to run HyperV tests
  AutomationManager.ps1
  AzureTestSuite.ps1
  Libraries/Azure.psm1
  Libraries/CommonFunctions.psm1
  Libraries/Framework.psm1
  Libraries/HyperV.psm1
  RunTests.ps1
  Testscripts/Windows/BVT-CAPTURE-VHD.ps1
  Testscripts/Windows/BVT-HVMODULES-CHECK.ps1
  Testscripts/Windows/BVT-IS-ROOT-PASSWORD-DELETED.ps1
  Testscripts/Windows/BVT-LAST-CONSOLE-CHECK.ps1
  Testscripts/Windows/BVT-MTAB-ENTRY-CHECK.ps1
  Testscripts/Windows/BVT-PASSWD-POLICY-TEST.ps1
  Testscripts/Windows/BVT-ROOT-DEVICE-TIMEOUT-CHECK.ps1
  Testscripts/Windows/BVT-SWAP-CHECK.ps1
  Testscripts/Windows/BVT-VERIFY-BASH-HISTORY.ps1
  Testscripts/Windows/BVT-VERIFY-BOOT-ERROR-WARNINGS.ps1
  Testscripts/Windows/BVT-VERIFY-DEPLOYMENT-PROVISION.ps1
  Testscripts/Windows/BVT-VERIFY-DISKSIZE.ps1
  Testscripts/Windows/BVT-VERIFY-KVP-DAEMON-STATUS.ps1
  Testscripts/Windows/BVT-VERIFY-NO-ERROR-IN-LOGS.ps1
  Testscripts/Windows/BVT-VERIFY-PRIVATEKEY-AUTHENTICATION.ps1
  Testscripts/Windows/BVT-VERIFY-RESTART.ps1
  Testscripts/Windows/BVT-VERIFY-SHUTDOWN.ps1
  Testscripts/Windows/BVT-VERIFY-SSHD-CONFIG.ps1
  Testscripts/Windows/BVT-VERIFY-UUID-FSTAB.ps1
  Testscripts/Windows/BVT-VERIFY-VERBOSE-ENABLED-LOGS.ps1
  Testscripts/Windows/BVT-VERIFY-VHD-PREREQUISITES.ps1
  Testscripts/Windows/CAPTURE-VHD-BEFORE-TEST.ps1
  Testscripts/Windows/DEMO-TEST-Aborted.ps1
  Testscripts/Windows/DEMO-TEST-FAIL.ps1
  Testscripts/Windows/DEMO-TEST-PASS.ps1
  Testscripts/Windows/DiskHotAddRemove-Parallel.ps1
  Testscripts/Windows/FILE-SYSTEM-VERIFICATION-TESTS.ps1
  Testscripts/Windows/HotReSize-VM.ps1
  Testscripts/Windows/LINUX-TEST-PROJECT-TESTS.ps1
  Testscripts/Windows/PERF-NETWORK-TCP-LATENCY-MULTICONNECTION-LAGSCOPE.ps1
  Testscripts/Windows/PERF-NETWORK-TCP-THROUGHPUT-MULTICONNECTION-NTTTCP.ps1
  Testscripts/Windows/PERF-NETWORK-UDP-THROUGHPUT-MULTICONNECTION-IPERF3.ps1
  Testscripts/Windows/PERF-STORAGE-MULTIDISK-RAID0-FIO.ps1
  Testscripts/Windows/PERF-STORAGE-OVER-NFS.ps1
  Testscripts/Windows/RHUI-BVT-VERIFY-RPM-SOURCE.ps1
  Testscripts/Windows/RUN-SCRIPT-IN-LINUX-GUEST.ps1
  Testscripts/Windows/VERIFY-DPDK-BUILD-AND-TESTPMD-TEST.ps1
  Testscripts/Windows/VERIFY-NVIDIA-CUDA-DRIVER-INSTALLATION.ps1
  Testscripts/Windows/VERIFY-TEST-SCRIPT-IN-LINUX-GUEST.ps1
  Testscripts/Windows/WALA-PROCESS-CHECK.ps1
  Testscripts/Windows/WALA-RESOURCE-DISK-FILESYSTEM-CHECK.ps1
  Testscripts/Windows/WALA-VERIFY-FIREWALL-STATUS.ps1
  Testscripts/Windows/WALA-VERIFY-HOSTNAME.ps1
  Testscripts/Windows/WALA-VERIFY-MNT-RESOURCE-README.ps1
  Testscripts/Windows/WALA-VERIFY-MNT-RESOURCE-WRITABLE.ps1
  Testscripts/Windows/WALA-VERSION-CHECK.ps1
  Utilities/UpdateGlobalConfigurationFromXmlSecrets.ps1
  Utilities/UploadFilesToStorageAccount.ps1
  XML/AzureVMSizeToHyperVMapping.xml
  XML/GlobalConfigurations.xml
  XML/TestCases/BVT.xml
  XML/TestCases/PerformanceTests.xml
  XML/TestCases/SmokeTests.xml
Labels: New Testcase, enhancement

#81 Added SLES 15 support for DPDK + Database
  Testscripts/Linux/dpdkSetup.sh
  Testscripts/Linux/dpdkTestPmd.sh
  Testscripts/Windows/VERIFY-DPDK-BUILD-AND-TESTPMD-TEST.ps1
  XML/TestCases/FunctionalTests-DPDK.xml
Labels: enhancement

#85 Add nested KVM NTTTCP test for private bridge network
  AutomationManager.ps1
  Testscripts/Linux/azuremodules.sh
  Testscripts/Linux/nested_kvm_basic_test.sh
  Testscripts/Linux/nested_kvm_ntttcp_private_bridge.sh
  Testscripts/Windows/NESTED-KVM-NTTTCP-PRIVATE-BRIDGE.ps1
  XML/TestCases/NestedKvmTests.xml
Labels: New Testcase

#98 Revert "Set theme jekyll-theme-tactile"
  _config.yml
Labels: bug

#101 Fixed Stress Category
  XML/TestCases/StressTests.xml
Labels: bug

#104 Juhlee/release model doc
  Documents/LISAv2ReleaseDiagram.jpg
  Documents/Release-model.md
Labels: enhancement

#105 Removal-Variable exception in final block
  RunTests.ps1
Labels: bug

#110 Juhlee/removal binaries
  README.md
  RunTests.ps1
  Tools/7za.exe
  Tools/dos2unix.exe
  Tools/gawk
  Tools/jq
  Tools/plink.exe
  Tools/pscp.exe
Labels: bug

#114 Juhlee/import ext scripts
  .gitignore
  Documents/Azure VNET automation/SETUP-TEST-ENVIRONMENT.txt
  Libraries/CommonFunctions.psm1
  Testscripts/Linux/perf_ntttcp.sh
  Testscripts/Linux/report-ntttcp-and-tcping.sh
  Testscripts/Linux/run-ntttcp-and-tcping.sh
Labels: bug

#113 Juhlee/add blob access
  README.md
  RunTests.ps1
Labels: bug

#118 jq file copying location to local
  Utilities/CheckTestPipelineRemotely.sh
  Utilities/LaunchTestPipelineRemotely.sh
Labels: bug

#106 Added SRIOV Azure tests for image checks
  Testscripts/Linux/verify-ifup-nics.sh
  XML/TestCases/FunctionalTests-SRIOV.xml
  XML/TestCases/StressTests.xml
  XML/VMConfigurations/SmokeTestsConfigurations.xml
Labels: enhancement
