Repository LIS/LISAv2, pull requests merged in 2018-08, with the labels that each got.

#120 Logging changed
  RunTests.ps1
Labels: bug

#119 two lines missing in last check-in
  Testscripts/Linux/run-ntttcp-and-tcping.sh
Labels: bug

#124 Updated scripts and document for 2nd supported platform
  AutomationManager.ps1
  AzureTestSuite.ps1
  README.md
  RunTests.ps1
Labels: enhancement

#125 Fixed the flow for customKernel case
  Libraries/Framework.psm1
Labels: bug

#95 Added support for SLES 15
  Libraries/CommonFunctions.psm1
  Testscripts/Linux/DetectLinuxDistro.sh
  Testscripts/Linux/Linux-Test-Project-Tests.sh
  Testscripts/Linux/perf_fio.sh
  Testscripts/Linux/perf_iperf3.sh
  Testscripts/Linux/perf_lagscope.sh
  Testscripts/Linux/perf_ntttcp.sh
  Testscripts/Windows/PERF-NETWORK-TCP-THROUGHPUT-MULTICONNECTION-NTTTCP.ps1
  Testscripts/Windows/PERF-NETWORK-UDP-THROUGHPUT-MULTICONNECTION-IPERF3.ps1
  XML/TestCases/CommunityTests.xml
  XML/TestCases/PerformanceTests.xml
Labels: enhancement

#136 Fixed non Microsoft blob access for FIO test
  Testscripts/Linux/perf_fio.sh
  Testscripts/Windows/PERF-STORAGE-MULTIDISK-RAID0-FIO.ps1
  XML/TestCases/PerformanceTests.xml
Labels: enhancement

#140 Stress category format fix
  XML/TestCases/StressTests.xml
Labels: bug

#146 Fixed broken ntttcp test
  Testscripts/Windows/PERF-NETWORK-TCP-THROUGHPUT-MULTICONNECTION-NTTTCP.ps1
  XML/TestCases/PerformanceTests.xml
Labels: bug

#145 Revert "Fix the case XMLSecretFile is not set, and only copy back test results"
  RunTests.ps1
Labels: bug

#144 Fixed : LISAv2 not exiting with correct exit code
  RunTests.ps1
Labels: bug

#139 azure: Fix SRIOV test VERIFY-IFUP-NICS-SRIOV
  Libraries/Test-Framework.psm1
  Testscripts/Linux/utils.sh
  Testscripts/Linux/verify-ifup-nics.sh
  XML/TestCases/FunctionalTests-SRIOV.xml
Labels: bug

#150 Fixed : VERIFY-DEPLOYMENT-PROVISION-SRIOV
  XML/TestCases/SmokeTests.xml
Labels: bug

#151 Fixed : PERF-NETWORK-UDP-THROUGHPUT-MULTICONNECTION-SRIOV
  XML/TestCases/PerformanceTests.xml
Labels: bug

#135 Fixed non Microsoft blob access for kernel-devel rpms
  Testscripts/Linux/customLISInstall.sh
Labels: enhancement

#155 Fixed issue of collecting VM logs
  Libraries/CommonFunctions.psm1
Labels: bug

#156 Fixed : Enable-RootUser showing password on console
  Libraries/Test-Framework.psm1
Labels: enhancement

#159 Fixed an issue where results were failing to upload to DB
  Testscripts/Windows/PERF-NETWORK-TCP-SINGLE-CONNECTION-THROUGHPUT.ps1
Labels: bug

#164 FIO : Minor fix
  Testscripts/Windows/PERF-STORAGE-MULTIDISK-RAID0-FIO.ps1
Labels: bug

#158 hyper-v: KVP test suite port from older lisa
  Libraries/CommonFunctions.psm1
  Libraries/Test-Framework.psm1
  Testscripts/Linux/KVP-AddKeyValues.sh
  Testscripts/Linux/KVP-BasicChecks.sh
  Testscripts/Linux/utils.sh
  Testscripts/Windows/BVT-UTILS.ps1
  Testscripts/Windows/KVP-AddKeyValues.ps1
  Testscripts/Windows/KVP-DeleteNonExistKVPOnGuest.ps1
  Testscripts/Windows/KVP-Intrinsic.ps1
  Testscripts/Windows/KVP-MaxRead.ps1
  Testscripts/Windows/KVP-ModifyKeyValues.ps1
  Testscripts/Windows/KVP-ModifyNonExistKVPOnGuest.ps1
  Testscripts/Windows/KVP-PushKeyValues.ps1
  Testscripts/Windows/KVP-RemoveKeyValues.ps1
  Testscripts/Windows/KVP-TestRescind.ps1
  Testscripts/Windows/SQM-Basic.ps1
  XML/TestCases/BVT.xml
  XML/TestCases/FunctionalTests.xml
Labels: New Testcase

#167 Updated the FIO VM size to Standard_DS14_v2
  XML/VMConfigurations/PerformanceTestsConfigurations.xml
Labels: Legacy code, bug

#162 DPDK pps testcases
  Testscripts/Linux/dpdk-testPMD.sh
  Testscripts/Linux/dpdkSetupAndRunTest.sh
  Testscripts/Linux/dpdkUtils.sh
  Testscripts/Linux/utils.sh
  Testscripts/Windows/DPDK-TESTCASE-DRIVER.ps1
  Testscripts/Windows/dpdk-testPMD.ps1
  XML/Other/pps_lowerbound.xml
  XML/TestCases/PerformanceTests-DPDK.xml
  XML/VMConfigurations/PerformanceTestsConfigurations.xml
Labels: New Testcase

#161 Add new case: nested kvm storage perf test for Azure and HyperV
  Libraries/Framework.psm1
  Libraries/HyperV.psm1
  RunTests.ps1
  Testscripts/Linux/nested_kvm_basic_test.sh
  Testscripts/Linux/nested_kvm_ntttcp_private_bridge.sh
  Testscripts/Linux/nested_kvm_perf_fio.sh
  Testscripts/Linux/nested_kvm_storage_perf.sh
  Testscripts/Linux/nested_kvm_utils.sh
  Testscripts/Linux/utils.sh
  Testscripts/Windows/NESTED-KVM-STORAGE-PERF.ps1
  Utilities/UpdateNestedTestParameters.ps1
  XML/TestCases/NestedKvmTests.xml
  XML/VMConfigurations/NestedVmTestsConfigurations.xml
Labels: New Testcase

#175 Fixed issue of LTP complete results are not being downloaded
  Testscripts/Linux/Linux-Test-Project-Tests.sh
Labels: bug
