Repository LIS/LISAv2, pull requests merged in 2018-11, with the labels that each got.

#348 customKernelInstall: Remove hyperv-tools on rhel
  Testscripts/Linux/customKernelInstall.sh
Labels: enhancement

#349 azure: ARMImageName param can be empty when OSVhd is set
  Libraries/CommonFunctions.psm1
  Libraries/Framework.psm1
Labels: enhancement

#345 Updated Syscall test script to upload results into database.
  Testscripts/Windows/PERF-SYSCALL-BENCHMARK.ps1
Labels: enhancement

#343 Auto-Format Azure.psm1 using VSCode (no logic change)
  Libraries/Azure.psm1
Labels: bug, enhancement

#339 Hyper-v: Dynamic Memory 5 test cases
  Libraries/CommonFunctions.psm1
  Testscripts/Windows/DM-CONFIGURE-MEMORY.ps1
  Testscripts/Windows/DM-HOTADD-STRESS-APP.ps1
  Testscripts/Windows/DM-HOTADD-STRESS-NG.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests.xml
Labels: New Testcase

#337 Hyper-V: VSS Backup 6 Test cases
  Libraries/CommonFunctions.psm1
  Testscripts/Linux/PartitionMultipleDisks.sh
  Testscripts/Linux/STOR_VSS_Check_VSS_Daemon.sh
  Testscripts/Linux/STOR_VSS_Disk_Mount_Multi_Paths.sh
  Testscripts/Linux/STOR_VSS_Disk_Mount_Squashfs.sh
  Testscripts/Linux/STOR_VSS_Set_VSS_Daemon.sh
  Testscripts/Linux/utils.sh
  Testscripts/Windows/PRODUCTION-CHECKPOINT-3CHAIN-VHD.ps1
  Testscripts/Windows/PRODUCTION-CHECKPOINT-ISO-NONETWORK.ps1
  Testscripts/Windows/STOR-VSS-3Chain-VHD-backup.ps1
  Testscripts/Windows/STOR-VSS-BACKUP-RESTORE-PARTITION.ps1
  Testscripts/Windows/STOR-VSS-Backup-Change-Hypervvssd.ps1
  Testscripts/Windows/STOR-VSS-BackupRestore-ISO-NoNetwork.ps1
  Testscripts/Windows/STOR-VSS-BackupRestore-Mount-Multi-Paths.ps1
  Testscripts/Windows/STOR-VSS-BackupRestore-Mount-Squashfs.ps1
  Testscripts/Windows/STOR-VSS-BackupRestore-State.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests.xml
Labels: New Testcase

#356 Add 2 & 3 VMs configuration for DM tests
  XML/VMConfigurations/FunctionalTestsConfigurations.xml
Labels: enhancement

#359 azure-pipelines.yml: remove publish artifacts
  azure-pipelines.yml
Labels: enhancement

#361 Add Priority for each case
  XML/TestCases/BVT.xml
  XML/TestCases/CommunityTests.xml
  XML/TestCases/FunctionalTests-DPDK.xml
  XML/TestCases/FunctionalTests-GPU.xml
  XML/TestCases/FunctionalTests-InfiniBand.xml
  XML/TestCases/FunctionalTests-SRIOV.xml
  XML/TestCases/FunctionalTests-Synthetic.xml
  XML/TestCases/FunctionalTests-WALA.xml
  XML/TestCases/FunctionalTests.xml
  XML/TestCases/NestedVmTests.xml
  XML/TestCases/PerformanceTests-DPDK.xml
  XML/TestCases/PerformanceTests.xml
  XML/TestCases/SmokeTests.xml
  XML/TestCases/StressTests.xml
Labels: enhancement

#363 Fixed the typo in logging
  Run-LisaV2.ps1
  Testscripts/Windows/PERF-NETWORK-TCP-SINGLE-CONNECTION-THROUGHPUT.ps1
  Utilities/AnalyseAllResults.ps1
Labels: bug

#364 azuremodules.py: Fix issue in distro detection
  Testscripts/Linux/azuremodules.py
Labels: bug

#368 framework: $OsVHD/$ARMImageName parameter bugfix
  Libraries/Framework-Azure.psm1
Labels: bug

#370 SR-IOV-Utils.sh: Function fix for SLES15
  Testscripts/Linux/SR-IOV-Utils.sh
Labels: bug

#369 framework: Multiple test areas at runtime
  Libraries/Framework-Azure.psm1
Labels: enhancement

#372 FunctionalTests.xml: Refresh category/area/tags
  XML/TestCases/FunctionalTests-SRIOV.xml
  XML/TestCases/FunctionalTests.xml
Labels: bug

#373 Update code for Priority changed
  Utilities/Get-LISAv2Statistics.ps1
  XML/TestCases/FunctionalTests-InfiniBand.xml
Labels: enhancement

#375 Replace BVTDeployment using SingleVM, they are duplicated
  Documents/Azure BVT automation/BVT-HVMODULES-CHECK.txt
  Documents/Azure BVT automation/BVT-IS-ROOT-PASSWORD-DELETED.txt
  Documents/Azure BVT automation/BVT-RESOURCE-DISK-FILESYSTEM.txt
  Documents/Azure BVT automation/BVT-ROOT-DEVICE-TIMEOUT-CHECK.txt
  Documents/Azure BVT automation/BVT-SWAP-CHECK.txt
  Documents/Azure BVT automation/BVT-VERIFY-BOOT-ERROR-WARNINGS.txt
  Documents/Azure BVT automation/BVT-VERIFY-DEPLOYMENT-PROVISION.txt
  Documents/Azure BVT automation/BVT-VERIFY-DISKSIZE.txt
  Documents/Azure BVT automation/BVT-VERIFY-FIREWALL-STATUS.txt
  Documents/Azure BVT automation/BVT-VERIFY-HOSTNAME.txt
  Documents/Azure BVT automation/BVT-VERIFY-MNT-RESOURCE-WRITABLE.txt
  Documents/Azure BVT automation/BVT-VERIFY-RESTART.txt
  Documents/Azure BVT automation/BVT-VERIFY-SHUTDOWN.txt
  Documents/Azure BVT automation/BVT-VERIFY-UUID-FSTAB.txt
  Documents/Azure BVT automation/BVT-WA-PROC-CHECK.txt
  Documents/Azure BVT automation/BVT-WA-VER-CHECK.txt
  XML/TestCases/BVT.xml
  XML/TestCases/FunctionalTests-WALA.xml
  XML/VMConfigurations/SmokeTestsConfigurations.xml
Labels: enhancement

#381 unit_tests: Fixed pester tests
  UnitTests/PowerShell/Libraries.Azure.Tests.ps1
  UnitTests/PowerShell/Libraries.CommonFunctions.Tests.ps1
  UnitTests/PowerShell/Libraries.ExtensionLibrary.Tests.ps1
  UnitTests/PowerShell/Libraries.Framework-Azure.Tests.ps1
  UnitTests/PowerShell/Libraries.Framework-HyperV.Tests.ps1
  UnitTests/PowerShell/Libraries.HyperV.Tests.ps1
  azure-pipelines.yml
Labels: enhancement

#382 Fixed issues from PR377
  Testscripts/Windows/BVT-NET-IFUP-IFDOWN.ps1
  XML/TestCases/BVT.xml
Labels: bug

#384 Fixing issue #26
  Testscripts/Linux/BVT-VERIFY-BOOT-ERROR-WARNINGS.py
Labels: enhancement

#354 Bug Fix for Run_time_memory_resize
  Testscripts/Windows/RUNTIME-MEM-CONFIGURE.ps1
  Testscripts/Windows/RUNTIME-MEM-HOTADD.ps1
  Testscripts/Windows/RUNTIME_MEM_HOTADD_CHUNKS.ps1
  Testscripts/Windows/RUNTIME_MEM_HOTADD_REBOOT.ps1
  Testscripts/Windows/RUNTIME_MEM_MULTIPLEADDREMOVE.ps1
  Testscripts/Windows/RUNTIME_MEM_STRESSHOTREMOVE.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests.xml
Labels: bug

#378 Fix BVT-VERIFY-SHUTDOWN for log collecting
  Testscripts/Windows/BVT-VERIFY-SHUTDOWN.ps1
Labels: bug

#386 handle the tool availability check in a more clear way
  Libraries/Framework-Azure.psm1
Labels: enhancement

#376 Hyper-v: Added STOR-VSS-BACKUPRESTORE-MULTIFS-VHDX test
  Testscripts/Windows/AddVhdxHardDisk.ps1
  XML/TestCases/FunctionalTests.xml
Labels: New Testcase

#389 Fix kernel install hanging issue
  Libraries/CommonFunctions.psm1
Labels: bug

#366 Hyper-V: Dynamic Memory 2 Test cases
  Libraries/HyperV.psm1
  Testscripts/Linux/utils.sh
  Testscripts/Windows/DM-SAVE-RESTORE.ps1
  Testscripts/Windows/DM_HIGH-PRIORITY.ps1
  Testscripts/Windows/DM_REMOVE-UNDER-PRESSURE.ps1
  XML/TestCases/FunctionalTests.xml
Labels: New Testcase

#393 customKernelInstall.sh: Fix for PR 357
  Testscripts/Linux/customKernelInstall.sh
Labels: bug

#387 Refine LISAv2 framework code
  AutomationManager.ps1
  AzureTestSuite.ps1
  Libraries/CommonFunctions.psm1
  Libraries/Framework-Azure.psm1
  Run-LisaV2.ps1
  Utilities/AddAzureRmAccountFromSecretsFile.ps1
Labels: enhancement

#396 Cleanup AddAzureRmAccountFromSecretsFile.ps1
  Utilities/AddAzureRmAccountFromSecretsFile.ps1
Labels: bug, enhancement

#398 Cleanup the framework code
  .gitignore
  AutomationManager.ps1
  AzureTestSuite.ps1
  Libraries/Azure.psm1
  Run-LisaV2.ps1
  Utilities/AddAzureRmAccountFromSecretsFile.ps1
Labels: enhancement

#397 Update document
  README.md
  XML/TestParameters.xml
Labels: enhancement

#367 Hyper-V: Added 3 new test-cases for Dynamic memory
  Testscripts/Windows/DM_CleanShutdown.ps1
  Testscripts/Windows/DM_HotAddRemove.ps1
  Testscripts/Windows/DM_StartupLowCompete.ps1
  XML/TestCases/FunctionalTests.xml
Labels: New Testcase

#383 Add two nested VM cases against Hyper-V and azure platforms
  Libraries/HyperV.psm1
  Testscripts/Linux/nested_hyperv_ntttcp_different_l1_nat.sh
  Testscripts/Linux/nested_kvm_netperf_pps.sh
  Testscripts/Linux/nested_kvm_netperf_pps_nat.sh
  Testscripts/Linux/nested_vm_utils.sh
  Testscripts/Windows/NESTED-HYPERV-NTTTCP-DIFFERENT-L1-NAT.ps1
  Testscripts/Windows/NESTED-KVM-NETPERF-PPS.ps1
  XML/TestCases/NestedVmTests.xml
  XML/VMConfigurations/NestedVmTestsConfigurations.xml
Labels: New Testcase

#402 LISAv2 code cleanup and improve
  AzureTestSuite.ps1
  JenkinsPipelines/Scripts/DeletePartnerFiles.ps1
  Libraries/Azure.psm1
  Libraries/CommonFunctions.psm1
  Libraries/Framework-Azure.psm1
  Libraries/HyperV.psm1
  Run-LisaV2.ps1
  Testscripts/Windows/FILE-SYSTEM-VERIFICATION-TESTS.ps1
  Testscripts/Windows/NESTED-HYPERV-NTTTCP-DIFFERENT-L1-NAT.ps1
  Testscripts/Windows/NESTED-KVM-NETPERF-PPS.ps1
Labels: enhancement

#374 Refactor code to enable reusing VM in multiple tests
  AutomationManager.ps1
  AzureTestSuite.ps1
  Libraries/Azure.psm1
  Libraries/CommonFunctions.psm1
  Libraries/Framework-HyperV.psm1
  Libraries/HyperV.psm1
  Run-LisaV2.ps1
Labels: enhancement

#403 Fix extra spaces in the test output for Total Test Cases
  AutomationManager.ps1
Labels: enhancement

#412 documentation: readme file update
  README.md
Labels: enhancement

#411 azure: get kernel logs in case of boot fail
  Libraries/Azure.psm1
  Libraries/CommonFunctions.psm1
Labels: enhancement

#405 pr_checker: Added PowerShell/Python/Bash checks
  Testscripts/Linux/BVT-PASSWD-POLICY-TEST.py
  Testscripts/Linux/BVT-VERIFY-BOOT-ERROR-WARNINGS.py
  Testscripts/Linux/BVT-VERIFY-DISKSIZE.py
  Testscripts/Linux/BVT-VERIFY-NO-ERROR-IN-LOGS.py
  Testscripts/Linux/BVT-VERIFY-SSHD-CONFIG.py
  Testscripts/Linux/BVT-VERIFY-UUID-FSTAB.py
  Testscripts/Linux/BVT-VERIFY-VERBOSE-ENABLED-LOGS.py
  Testscripts/Linux/BVT-VERIFY-VHD-PREREQUISITES.py
  Testscripts/Linux/WALA-PROCESS-CHECK.py
  Testscripts/Linux/WALA-VERIFY-FIREWALL-STATUS.py
  Testscripts/Linux/WALA-VERIFY-HOSTNAME.py
  Testscripts/Linux/WALA-VERIFY-MNT-RESOURCE-WRITABLE.py
  Testscripts/Linux/WALA-VERSION-CHECK.py
  Testscripts/Linux/azuremodules.py
  Testscripts/Linux/nslookup.py
  Testscripts/Windows/NESTED-HYPERV-STORAGE-PERF.ps1
  Utilities/commit-finder.ps1
  azure-pipelines.yml
Labels: enhancement

#420 kernel_logs: fix initial log file
  Libraries/CommonFunctions.psm1
Labels: bug

#418 Hyper-V: Added VHDX-Resize Live Migration test-case
  Testscripts/Windows/AddVhdxHardDisk.ps1
  Testscripts/Windows/STOR_VHDXRESIZE_BASICLM.ps1
  XML/TestCases/FunctionalTests.xml
Labels: enhancement

#410 Hyper-V: Added 10 test-cases for Live Migration
  Testscripts/Windows/Migrate-VM.ps1
  Testscripts/Windows/NET-LIVEMIG.ps1
  Testscripts/Windows/SETUP-Change-CPU.ps1
  XML/TestCases/FunctionalTests.xml
Labels: New Testcase

#417 Refactor the test framework code
  Libraries/CommonFunctions.psm1
  Libraries/Framework-Azure.psm1
  Libraries/WorkingSpaceManagement.psm1
  Libraries/XmlProcessing.psm1
  Run-LisaV2.ps1
Labels: CodeRefactoring

#421 code cleanup: remove TC_COVERED references
  Testscripts/Linux/BVT-NET-ETHTOOL-CHECK-KEYS.sh
  Testscripts/Linux/KVP-AddKeyValues.sh
  Testscripts/Linux/provisionLinuxForLisa.sh
  Testscripts/Windows/KDUMP-TestScript.ps1
  Testscripts/Windows/KVP-Intrinsic.ps1
  Testscripts/Windows/KVP-PushKeyValues.ps1
  Testscripts/Windows/SQM-Basic.ps1
  XML/TestCases/BVT.xml
  XML/TestCases/CommunityTests.xml
  XML/TestCases/FunctionalTests.xml
  XML/TestCases/StressTests.xml
Labels: Legacy code

#425 penguinator: fix LogFileName in scripts
  JenkinsPipelines/Scripts/InspectVHD.ps1
  JenkinsPipelines/Scripts/ReceivePartnerFiles.ps1
Labels: bug

#427 BVT-TimeSync_NTP.sh: skip test if ntp is not supported
  Testscripts/Linux/BVT-CORE-TIMESYNC-NTP.sh
Labels: enhancement

#426 Modify relative path to absolute path.
  Testscripts/Windows/DPDK-TESTCASE-DRIVER.ps1
  Testscripts/Windows/NESTED-HYPERV-STORAGE-PERF.ps1
  Testscripts/Windows/NESTED-KVM-NTTTCP-PRIVATE-BRIDGE.ps1
  Testscripts/Windows/NESTED-KVM-STORAGE-PERF.ps1
  Testscripts/Windows/PERF-NETWORK-TCP-LATENCY-MULTICONNECTION-LAGSCOPE.ps1
  Testscripts/Windows/PERF-NETWORK-TCP-NETPERF.ps1
  Testscripts/Windows/PERF-NETWORK-TCP-SINGLE-CONNECTION-THROUGHPUT.ps1
  Testscripts/Windows/PERF-NETWORK-THROUGHPUT-MULTICONNECTION-NTTTCP.ps1
  Testscripts/Windows/PERF-NETWORK-UDP-THROUGHPUT-MULTICONNECTION-IPERF3.ps1
  Testscripts/Windows/PERF-STORAGE-MULTIDISK-RAID0-FIO.ps1
  Testscripts/Windows/PERF-STORAGE-OVER-NFS.ps1
  Testscripts/Windows/PERF-SYSCALL-BENCHMARK.ps1
  Testscripts/Windows/VERIFY-DPDK-BUILD-AND-TESTPMD-TEST.ps1
  Testscripts/Windows/VERIFY-DPDK-COMPLIANCE.ps1
  Testscripts/Windows/VERIFY-INFINIBAND-MultiVM.ps1
  Testscripts/Windows/VERIFY-NVIDIA-CUDA-DRIVER-INSTALLATION.ps1
  Testscripts/Windows/VERIFY-SRIOV-FAILSAFE-FOR-DPDK.ps1
Labels: bug

#385 Implementation for VM creation on cluster
  Libraries/Framework-HyperV.psm1
  Libraries/HyperV.psm1
  Testscripts/Windows/SECUREBOOT.ps1
  XML/TestCases/FunctionalTests.xml
  XML/VMConfigurations/FunctionalTestsConfigurations.xml
Labels: New Feature

#423 Add a parameter TestPriority, to enable run test by priority
  Libraries/Framework-Azure.psm1
  Libraries/XmlProcessing.psm1
  Run-LisaV2.ps1
Labels: New Feature

#430 Merge AzureTestSuite.ps1 and remove useless switches
  AutomationManager.ps1
  AzureTestSuite.ps1
  Libraries/CommonFunctions.psm1
  Libraries/Framework-Azure.psm1
  Run-LisaV2.ps1
Labels: Legacy code

#362 Azure, Hyper-V: Add new test case for web stress test with http_load
  Testscripts/Linux/SR-IOV-Utils.sh
  Testscripts/Linux/stress_web.sh
  Testscripts/Windows/SETUP-SR-IOV-Configure.ps1
  Testscripts/Windows/STRESS-Web.ps1
  XML/TestCases/StressTests.xml
Labels: New Testcase

#436 penguinator: fixed remaining LogFileName errors
  JenkinsPipelines/Scripts/DeletePartnerFiles.ps1
  JenkinsPipelines/Scripts/DetectTestRegions.ps1
  JenkinsPipelines/Scripts/GetPartnerStorageUsage.ps1
  JenkinsPipelines/Scripts/InspectCustomKernel.ps1
  JenkinsPipelines/Scripts/JenkinsTestSelectionMenuGenerator.ps1
  JenkinsPipelines/Scripts/PrepareEnvOfNestedVMsTestOnHyperv.ps1
  JenkinsPipelines/Scripts/UpdateAzureRegionAndVMSizes.ps1
  JenkinsPipelines/Scripts/UpdatePublisherImages.ps1
Labels: bug

#440 refactor: moved lisav2 functions to a separate file
  Libraries/CommonFunctions.psm1
  Libraries/Framework-HyperV.psm1
  Libraries/HyperV.psm1
  Libraries/LISAV2-Framework.psm1
  UnitTests/PowerShell/Libraries.Framework-Azure.Tests.ps1
  UnitTests/PowerShell/Libraries.LISAV2-Framework.Tests.ps1
Labels: CodeRefactoring

#435 Code refactor: Add LogProcessing.psm1 module for log,summary,report
  AutomationManager.ps1
  Libraries/CommonFunctions.psm1
  Libraries/LISAV2-Framework.psm1
  Libraries/LogProcessing.psm1
  Run-LisaV2.ps1
Labels: CodeRefactoring

#445 Fix Logfilename variable issue in Utilities scripts
  Utilities/AddAzureRmAccountFromSecretsFile.ps1
  Utilities/AnalyseAllResults.ps1
  Utilities/CopyVHDtoOtherStorageAccount.ps1
  Utilities/Get-AzureVMs.ps1
  Utilities/Get-SubscriptionUsage.ps1
  Utilities/Get-SubscriptionUsageTopVMs.ps1
  Utilities/ManageTestStorageAccounts.ps1
  Utilities/UploadVHDtoAzureStorage.ps1
Labels: bug

#444 No need enable root for testing on Azure.
  Libraries/LISAV2-Framework.psm1
Labels: enhancement

#457 Fix issue #452
  Utilities/AddAzureRmAccountFromSecretsFile.ps1
  Utilities/AnalyseAllResults.ps1
  Utilities/CopyVHDtoOtherStorageAccount.ps1
  Utilities/Get-AzureVMs.ps1
  Utilities/Get-SubscriptionUsage.ps1
  Utilities/Get-SubscriptionUsageTopVMs.ps1
  Utilities/ManageTestStorageAccounts.ps1
  Utilities/UploadVHDtoAzureStorage.ps1
Labels: bug

#442 hyperv: optimize resource consumption
  Libraries/CommonFunctions.psm1
  Libraries/HyperV.psm1
  Libraries/LISAV2-Framework.psm1
  Libraries/WorkingSpaceManagement.psm1
  Run-LisaV2.ps1
  UnitTests/PowerShell/Libraries.WorkingSpaceManagement.Tests.ps1
Labels: CodeRefactoring, enhancement

#463 Revert "No need enable root for testing on Azure. (#444)"
  Libraries/LISAV2-Framework.psm1
Labels: question

#466 Fix typo issue in BVT-VERIFY-SHUTDOWN
  Testscripts/Windows/BVT-VERIFY-SHUTDOWN.ps1
Labels: bug

#468 penguinator: Added StorageAccount parameter
  JenkinsPipelines/Run-Linux-Tests.groovy
Labels: enhancement

#473 Fix flake8 errors for new rules E302,H201,E231
  Testscripts/Linux/BVT-HVMODULES-CHECK.py
  Testscripts/Linux/BVT-IS-ROOT-PASSWORD-DELETED.py
  Testscripts/Linux/BVT-LAST-CONSOLE-CHECK.py
  Testscripts/Linux/BVT-MTAB-ENTRY-CHECK.py
  Testscripts/Linux/BVT-PASSWD-POLICY-TEST.py
  Testscripts/Linux/BVT-ROOT-DEVICE-TIMEOUT-CHECK.py
  Testscripts/Linux/BVT-SWAP-CHECK.py
  Testscripts/Linux/BVT-VERIFY-BASH-HISTORY.py
  Testscripts/Linux/BVT-VERIFY-BOOT-ERROR-WARNINGS.py
  Testscripts/Linux/BVT-VERIFY-DISKSIZE.py
  Testscripts/Linux/BVT-VERIFY-MNT-RESOURCE-README.py
  Testscripts/Linux/BVT-VERIFY-NO-ERROR-IN-LOGS.py
  Testscripts/Linux/BVT-VERIFY-SSHD-CONFIG.py
  Testscripts/Linux/BVT-VERIFY-UUID-FSTAB.py
  Testscripts/Linux/BVT-VERIFY-VERBOSE-ENABLED-LOGS.py
  Testscripts/Linux/BVT-VERIFY-VHD-PREREQUISITES.py
  Testscripts/Linux/WALA-PROCESS-CHECK.py
  Testscripts/Linux/WALA-RESOURCE-DISK-FILESYSTEM-CHECK.py
  Testscripts/Linux/WALA-VERIFY-HOSTNAME.py
  Testscripts/Linux/WALA-VERIFY-MNT-RESOURCE-README.py
  Testscripts/Linux/WALA-VERSION-CHECK.py
  Testscripts/Linux/azuremodules.py
  azure-pipelines.yml
Labels: enhancement
