Repository LIS/LISAv2, pull requests merged in 2018-09, with the labels that each got.

#178 Tag always should be lowercase
  XML/TestCases/CommunityTests.xml
Labels: bug

#180 XML tag format correction
  XML/TestCases/CommunityTests.xml
Labels: bug

#177 Added function name style guideline
  Documents/How-to-use.md
Labels: enhancement

#179 Add Tagging guideline
  Documents/How-to-use.md
  XML/TestCases/BVT.xml
  XML/TestCases/CommunityTests.xml
  XML/TestCases/FunctionalTests-SRIOV.xml
  XML/TestCases/Other.xml
  XML/TestCases/PerformanceTests.xml
Labels: enhancement

#185 Add a new PS script displaying test cases
  Get-LISAv2Statistics.ps1
Labels: enhancement

#191 Fixing the issue introduced in PR#168
  Libraries/CommonFunctions.psm1
Labels: LISAv2 Broken, bug

#187 New LISAv2 feature : Replaceable test parameters
  Libraries/Framework.psm1
  RunTests.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests-DPDK.xml
  XML/TestCases/PerformanceTests-DPDK.xml
  XML/TestCases/PerformanceTests.xml
Labels: enhancement

#189 Added support to install dpdk from given git or tar source link
  Testscripts/Linux/dpdkSetup.sh
  Testscripts/Linux/dpdkTestPmd.sh
  Testscripts/Windows/VERIFY-DPDK-BUILD-AND-TESTPMD-TEST.ps1
  XML/TestCases/FunctionalTests-DPDK.xml
Labels: enhancement

#197 LTP tests updated to use latest release version
  Testscripts/Linux/Linux-Test-Project-Tests.sh
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/CommunityTests.xml
Labels: enhancement

#184 Corrected function name format suggestion
  Documents/How-to-use.md
Labels: bug

#205 utils: Make sure the params are mandatory and PS libs loaded and fix PS function name
  Utilities/AddAzureRmAccountFromSecretsFile.ps1
  Utilities/UpdateGlobalConfigurationFromXmlSecrets.ps1
Labels: bug

#198 Updated script to upload multi-core dpdk results into database
  Testscripts/Linux/dpdk-testPMD.sh
  Testscripts/Linux/dpdkSetupAndRunTest.sh
  Testscripts/Linux/dpdkUtils.sh
  Testscripts/Windows/DPDK-TESTCASE-DRIVER.ps1
  Testscripts/Windows/VERIFY-DPDK-BUILD-AND-TESTPMD-TEST.ps1
  Testscripts/Windows/dpdk-testPMD.ps1
  XML/TestCases/PerformanceTests-DPDK.xml
Labels: bug

#203 Add distro short name and test result term
  Documents/How-to-use.md
Labels: help wanted

#188 New test case : Verify Enable-Disable SRIOV.
  Libraries/Azure.psm1
  Libraries/CommonFunctions.psm1
  Testscripts/Windows/VERIFY-ENABLE-DISABLE-SRIOV-ON-EXISTING-VM.ps1
  XML/TestCases/FunctionalTests-SRIOV.xml
Labels: New Testcase

#199 HyperV: LIS core tests backport
  Testscripts/Linux/LIS-Check-HypervDaemons-Files-Status.sh
  Testscripts/Linux/LIS-Mount-CD.sh
  Testscripts/Linux/LIS-Mount-FloppyDisk.sh
  Testscripts/Windows/LIS-Check-HypervDaemons-Files-Status.ps1
  Testscripts/Windows/LIS-Mount-CD.ps1
  Testscripts/Windows/LIS-Mount-FloppyDisk.ps1
  XML/TestCases/FunctionalTests.xml
Labels: New Testcase

#206 Fixed missing file bug in a test case.
  XML/TestCases/FunctionalTests-Synthetic.xml
Labels: bug

#196 framework: fix remote server run
  Libraries/Test-Framework.psm1
Labels: enhancement

#210 Fixed issue where RemoteCopy is returning empty string.
  Libraries/CommonFunctions.psm1
Labels: LISAv2 Broken, bug

#181 New Tests : Infiniband (Intel MPI)
  Testscripts/Linux/TestRDMA_MultiVM.sh
  Testscripts/Windows/VERIFY-INFINIBAND-MultiVM.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests-InfiniBand.xml
  XML/VMConfigurations/FunctionalTestsConfigurations.xml
Labels: New Testcase

#207 hyper-v: Added 9 network tests
  Libraries/CommonFunctions.psm1
  Libraries/Test-Framework.psm1
  Testscripts/Linux/NET-Max-NICs.sh
  Testscripts/Linux/NET-Operstate.sh
  Testscripts/Linux/NET-Test-Legacy.sh
  Testscripts/Linux/NET-Test-Network.sh
  Testscripts/Linux/NET-Test-Promiscuous.sh
  Testscripts/Windows/SETUP-Inject-IP-Constants.ps1
  Testscripts/Windows/SETUP-NET-Add-Max-NIC.ps1
  Testscripts/Windows/SETUP-NET-Add-NIC.ps1
  Testscripts/Windows/SETUP-NET-Switch-NIC.ps1
  XML/TestCases/FunctionalTests.xml
Labels: New Testcase

#208 Add nested network performance case, support 2 different hyper-v hosts
  AutomationManager.ps1
  Libraries/Azure.psm1
  Libraries/CommonFunctions.psm1
  Libraries/Framework.psm1
  Libraries/HyperV.psm1
  Libraries/Test-Framework.psm1
  RunTests.ps1
  Testscripts/Linux/nat_qemu_ifup.sh
  Testscripts/Linux/nested_hyperv_ntttcp_different_l1_public_bridge.sh
  Testscripts/Linux/nested_kvm_basic_test.sh
  Testscripts/Linux/nested_kvm_lagscope_different_l1_public_bridge.sh
  Testscripts/Linux/nested_kvm_ntttcp_different_l1_nat.sh
  Testscripts/Linux/nested_kvm_ntttcp_different_l1_public_bridge.sh
  Testscripts/Linux/nested_kvm_ntttcp_private_bridge.sh
  Testscripts/Linux/nested_kvm_perf_fio.sh
  Testscripts/Linux/nested_kvm_storage_perf.sh
  Testscripts/Linux/nested_vm_utils.sh
  Testscripts/Windows/AddVhdxHardDisk.ps1
  Testscripts/Windows/BVT-CORE-RELOAD-MODULES.ps1
  Testscripts/Windows/CORE-VerifyHeartBeat.ps1
  Testscripts/Windows/CORE-VerifyShutdown.ps1
  Testscripts/Windows/CORE-VerifyTimeSync.ps1
  Testscripts/Windows/FCOPY-BASIC.ps1
  Testscripts/Windows/FCOPY-DISABLE-ENABLE.ps1
  Testscripts/Windows/FCOPY-FILE-EXISTS.ps1
  Testscripts/Windows/FCOPY-LARGE-FILE.ps1
  Testscripts/Windows/FCOPY-NEGATIVE.ps1
  Testscripts/Windows/FCOPY-NON-ASCII.ps1
  Testscripts/Windows/FCOPY-OVERWRITE.ps1
  Testscripts/Windows/FCOPY-REPEATED-DELETE.ps1
  Testscripts/Windows/Heartbeat-PausedCritical.ps1
  Testscripts/Windows/KVP-AddKeyValues.ps1
  Testscripts/Windows/KVP-DeleteNonExistKVPOnGuest.ps1
  Testscripts/Windows/KVP-Intrinsic.ps1
  Testscripts/Windows/KVP-MaxRead.ps1
  Testscripts/Windows/KVP-ModifyKeyValues.ps1
  Testscripts/Windows/KVP-ModifyNonExistKVPOnGuest.ps1
  Testscripts/Windows/KVP-PushKeyValues.ps1
  Testscripts/Windows/KVP-RemoveKeyValues.ps1
  Testscripts/Windows/KVP-TestRescind.ps1
  Testscripts/Windows/LIS-Check-HypervDaemons-Files-Status.ps1
  Testscripts/Windows/LIS-Mount-CD.ps1
  Testscripts/Windows/LIS-Mount-FloppyDisk.ps1
  Testscripts/Windows/Max-vCPU.ps1
  Testscripts/Windows/NESTED-HYPERV-NTTTCP-DIFFERENT-L1-PUBLIC-BRIDGE.ps1
  Testscripts/Windows/NESTED-KVM-LAGSCOPE-DIFFERENT-L1-PUBLIC-BRIDGE.ps1
  Testscripts/Windows/NESTED-KVM-NTTTCP-DIFFERENT-L1-PUBLIC-BRIDGE.ps1
  Testscripts/Windows/NESTED-KVM-STORAGE-PERF.ps1
  Testscripts/Windows/NUMA-Test.ps1
  Testscripts/Windows/Reboot-Diff-Memory-Settings.ps1
  Testscripts/Windows/SETUP-Change-CPU.ps1
  Testscripts/Windows/SETUP-Config-VM.ps1
  Testscripts/Windows/SQM-Basic.ps1
  Testscripts/Windows/Timesync-Change-State.ps1
  XML/GlobalConfigurations.xml
  XML/TestCases/NestedKvmTests.xml
  XML/TestCases/NestedVmTests.xml
  XML/VMConfigurations/NestedVmTestsConfigurations.xml
Labels: New Testcase

#212 Combined test result and execution time in one line
  AzureTestSuite.ps1
  Libraries/CommonFunctions.psm1
Labels: enhancement

#213 TestCase name format should be all in upper cases.
  Documents/How-to-use.md
  XML/TestCases/FunctionalTests.xml
Labels: bug

#216 fix: Changed hvServer as required by PR208
  Testscripts/Windows/SETUP-Inject-IP-Constants.ps1
  Testscripts/Windows/SETUP-NET-Add-Max-NIC.ps1
  Testscripts/Windows/SETUP-NET-Add-NIC.ps1
  Testscripts/Windows/SETUP-NET-Switch-NIC.ps1
Labels: bug

#214 Added new test to verify SRIOV failsafe for DPDK
  Testscripts/Linux/dpdkTestPmd.sh
  Testscripts/Windows/VERIFY-SRIOV-FAILSAFE-FOR-DPDK.ps1
  XML/TestCases/FunctionalTests-DPDK.xml
Labels: New Testcase

#218 hyperv: Added VMBus tests
  Testscripts/Linux/KDUMP-Config.sh
  Testscripts/Linux/utils.sh
  Testscripts/Linux/verify_vmbus_interrupts.sh
  Testscripts/Linux/verify_vmbus_protocol_version.sh
  Testscripts/Windows/Check-VMBusPanicEvent.ps1
  XML/TestCases/FunctionalTests.xml
  XML/VMConfigurations/FunctionalTestsConfigurations.xml
Labels: New Testcase

#217 hyperv: Add LIS NMI tests
  Libraries/HyperV.psm1
  Testscripts/Linux/check_triggered_nmi.sh
  Testscripts/Windows/Check-VMBusPanicEvent.ps1
  Testscripts/Windows/Trigger-FailedNmiInterrupt.ps1
  Testscripts/Windows/Trigger-NmiInterrupt.ps1
  XML/TestCases/FunctionalTests.xml
Labels: New Testcase

#200 Added new test : Netperf for checking PPS performance
  Testscripts/Linux/perf_netperf.sh
  Testscripts/Linux/utils.sh
  Testscripts/Windows/PERF-NETWORK-TCP-NETPERF.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/PerformanceTests.xml
Labels: New Testcase

#204 HyperV, Azure: kdump tests
  Testscripts/Linux/KDUMP-Config.sh
  Testscripts/Linux/KDUMP-Execute.sh
  Testscripts/Linux/KDUMP-NFSconfig.sh
  Testscripts/Linux/KDUMP-Results.sh
  Testscripts/Windows/KDUMP-TestScript.ps1
  XML/TestCases/FunctionalTests.xml
Labels: New Testcase

#223 kdump: Fixed test case names
  XML/TestCases/FunctionalTests.xml
Labels: bug

#227 Updated script with latest CUDA version.
  Testscripts/Linux/InstallCUDADrivers.sh
  Testscripts/Windows/VERIFY-NVIDIA-CUDA-DRIVER-INSTALLATION.ps1
Labels: Legacy code, enhancement

#222 Implement Generation 2 Hyper-V VM support
  AutomationManager.ps1
  Libraries/CommonFunctions.psm1
  Libraries/Framework.psm1
  Libraries/HyperV.psm1
  Libraries/Test-Framework.psm1
  RunTests.ps1
Labels: New Testcase
