Repository LIS/LISAv2, pull requests merged in 2018-10, with the labels that each got.

#237 Notify in case specified test not found
  RunTests.ps1
Labels: enhancement

#239 STRESS: Added 4 test cases
  Testscripts/Linux/Sysbench.sh
  Testscripts/Windows/STRESS-BootLargeMemory.ps1
  Testscripts/Windows/STRESS-EventID-18602-Regression.ps1
  Testscripts/Windows/STRESS-MTU-Netvsc-Reload.ps1
  Testscripts/Windows/Set-VM-Memory.ps1
  XML/TestCases/StressTests.xml
Labels: New Testcase

#242 hyper-v: Increase retry count on getting IP
  Libraries/HyperV.psm1
Labels: enhancement

#245 enableRoot: Do sync to fix #244
  Testscripts/Linux/enableRoot.sh
Labels: bug

#238 Hyper-V: Added 14 NET test cases and support for secondary VM
  AzureTestSuite.ps1
  Libraries/CommonFunctions.psm1
  Libraries/HyperV.psm1
  Libraries/Test-Framework.psm1
  Testscripts/Linux/NET-Configure-Vxlan.sh
  Testscripts/Linux/NET-Copy-Both-Ways.sh
  Testscripts/Linux/NET-Copy-Different-MTU.sh
  Testscripts/Linux/NET-Copy-Large-File.sh
  Testscripts/Linux/NET-Corruption.sh
  Testscripts/Linux/NET-Ethtool-Check-Statistics.sh
  Testscripts/Linux/NET-Jumbo-Frames.sh
  Testscripts/Linux/NET-Multicast.sh
  Testscripts/Linux/NET-Netperf-Server.sh
  Testscripts/Linux/utils.sh
  Testscripts/Windows/NET-File-Copy-SCP.ps1
  Testscripts/Windows/NET-IP-Injection.ps1
  Testscripts/Windows/NET-TCP-Corruption.ps1
  Testscripts/Windows/NET-Test-Private-Network.ps1
  Testscripts/Windows/NET-Test-Vxlan.ps1
  Testscripts/Windows/NET-VLAN-Tagging.ps1
  Testscripts/Windows/NET-VLAN-Trunking.ps1
  Testscripts/Windows/SETUP-Inject-IP-Constants.ps1
  Testscripts/Windows/SETUP-NET-Add-NIC.ps1
  Testscripts/Windows/SETUP-NET-Configure-Dependency-VM.ps1
  Testscripts/Windows/SETUP-NET-Switch-NIC.ps1
  XML/TestCases/FunctionalTests.xml
  XML/VMConfigurations/FunctionalTestsConfigurations.xml
Labels: New Testcase, enhancement

#246 Fixed a breaking issue introduced in PR #238
  AzureTestSuite.ps1
Labels: LISAv2 Broken, bug

#230 Added new test to verify DPDK compliance
  Testscripts/Linux/dpdkSetup.sh
  Testscripts/Windows/VERIFY-DPDK-COMPLIANCE.ps1
  XML/TestCases/FunctionalTests-DPDK.xml
  XML/VMConfigurations/FunctionalTestsConfigurations.xml
Labels: New Testcase

#248 Fix log level and print an extra log
  Libraries/CommonFunctions.psm1
  Libraries/HyperV.psm1
  Libraries/Test-Framework.psm1
Labels: bug, enhancement

#251 Rename: RunTests.ps1 to Run-LisaV2.ps1
  JenkinsPipelines/Run-Boot-Stress-Tests.groovy
  JenkinsPipelines/Run-Linux-Tests.groovy
  README.md
  Run-LisaV2.ps1
  Testscripts/Linux/Linux-Test-Project-Tests.sh
  XML/Other/ReplaceableTestParameters.xml
Labels: enhancement

#260 Relocate statistics report file in Utilities folder
  Utilities/Get-LISAv2Statistics.ps1
Labels: enhancement

#261 Resolve issue for running code remotely
  Libraries/HyperV.psm1
Labels: bug

#243 New LISAv2 Feature : VirtualMachineSet
  Libraries/Framework.psm1
  Run-LisaV2.ps1
  RunTests.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests-InfiniBand.xml
  XML/VMConfigurations/FunctionalTestsConfigurations.xml
Labels: New Feature, enhancement

#267 Revert "New LISAv2 Feature : VirtualMachineSet"
  Libraries/Framework.psm1
  Run-LisaV2.ps1
  RunTests.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests-InfiniBand.xml
  XML/VMConfigurations/FunctionalTestsConfigurations.xml
Labels: bug

#252 hyper-v : Added 2 Storage test cases
  Testscripts/Linux/STOR-Lis-Disk.sh
  Testscripts/Windows/SETUP-STOR-TakeRevert-Snapshot.ps1
  Testscripts/Windows/STOR-ExportImportVM.ps1
  XML/TestCases/FunctionalTests.xml
Labels: New Testcase

#271 Removed non-mandatory param
  Utilities/AddAzureRmAccountFromSecretsFile.ps1
Labels: bug

#270 File path access changes
  Tools/Deleteme.txt
  Utilities/Get-LISAv2Statistics.ps1
Labels: bug

#263 Enhanced log searching
  Testscripts/Linux/BVT-CORE-TIME-CLOCKSOURCE.sh
  Testscripts/Linux/BVT-CORE-VERIFY-LIS-MODULES.sh
Labels: enhancement

#274 hyper-v : Added 1 Storage TC
  Testscripts/Linux/STOR-Verify-Sector-Size.sh
  XML/TestCases/FunctionalTests.xml
Labels: New Testcase

#272 Add keywords for COREOS when check dmesg to ignore them.
  XML/Other/ignorable-boot-errors.xml
Labels: enhancement

#264 hyper-v: Remove snapshots and not leak vhds
  Libraries/HyperV.psm1
Labels: enhancement

#232 Support tests cases against SLES15
  Testscripts/Linux/BVT-CORE-RELOAD-MODULES.sh
  Testscripts/Linux/BVT-CORE-TIME-CLOCKEVENT.sh
  Testscripts/Linux/BVT-CORE-TIME-CLOCKSOURCE.sh
  Testscripts/Linux/BVT-HVMODULES-CHECK.py
  Testscripts/Linux/BVT-NET-IFUP-IFDOWN.sh
  Testscripts/Linux/BVT-VERIFY-BOOT-ERROR-WARNINGS.py
  Testscripts/Linux/BVT-VERIFY-NO-ERROR-IN-LOGS.py
  Testscripts/Linux/BVT-VERIFY-UUID-FSTAB.py
  Testscripts/Linux/DetectLinuxDistro.sh
  Testscripts/Linux/utils.sh
  Testscripts/Linux/verify-ifdown-ifup-eth0-rmmod-modprobe-hv-netvsc.sh
  Testscripts/Windows/BVT-CORE-RELOAD-MODULES.ps1
  Testscripts/Windows/BVT-VERIFY-VHD-PREREQUISITES.ps1
Labels: enhancement

#258 Usage fix
  Utilities/Get-SubscriptionUsage.ps1
Labels: Legacy code, enhancement

#229 Add nested hyperv disk performance test cases against azure and hyperv
  AutomationManager.ps1
  Libraries/Azure.psm1
  Libraries/CommonFunctions.psm1
  Libraries/Framework.psm1
  Libraries/HyperV.psm1
  Libraries/Test-Framework.psm1
  Testscripts/Linux/fio_jason_parser.sh
  Testscripts/Windows/NESTED-HYPERV-NTTTCP-DIFFERENT-L1-PUBLIC-BRIDGE.ps1
  Testscripts/Windows/NESTED-HYPERV-STORAGE-PERF.ps1
  Utilities/UpdateNestedTestParameters.ps1
  XML/TestCases/NestedVmTests.xml
  XML/VMConfigurations/NestedVmTestsConfigurations.xml
Labels: New Testcase

#282 kernel_install: Added support for multiple kernel install files
  Libraries/CommonFunctions.psm1
  Testscripts/Linux/customKernelInstall.sh
Labels: enhancement

#287 hyper-v framework: deploy 2nd VM to a different host
  Libraries/CommonFunctions.psm1
  Libraries/HyperV.psm1
  Libraries/Test-Framework.psm1
  Testscripts/Linux/SR-IOV-Utils.sh
  Testscripts/Windows/SETUP-SR-IOV-Configure.ps1
  Testscripts/Windows/SRIOV-DISABLEVF-PING.ps1
  XML/AzureVMSizeToHyperVMapping.xml
  XML/TestCases/FunctionalTests-SRIOV.xml
  XML/VMConfigurations/FunctionalTestsConfigurations.xml
Labels: New Feature, enhancement

#290 Replaced with ThrowException fn
  AutomationManager.ps1
  AzureTestSuite.ps1
  Run-LisaV2.ps1
  Testscripts/Windows/BVT-VERIFY-DEPLOYMENT-PROVISION.ps1
  Testscripts/Windows/BVT-VERIFY-DISKSIZE.ps1
  Testscripts/Windows/BVT-VERIFY-KVP-DAEMON-STATUS.ps1
  Testscripts/Windows/BVT-VERIFY-PRIVATEKEY-AUTHENTICATION.ps1
  Testscripts/Windows/BVT-VERIFY-RESTART.ps1
  Testscripts/Windows/BVT-VERIFY-SHUTDOWN.ps1
  Testscripts/Windows/BVT-VERIFY-SSHD-CONFIG.ps1
  Testscripts/Windows/BVT-VERIFY-VHD-PREREQUISITES.ps1
  Testscripts/Windows/CAPTURE-VHD-BEFORE-TEST.ps1
  Testscripts/Windows/Check-VMBusPanicEvent.ps1
  Testscripts/Windows/DEMO-TEST-Aborted.ps1
  Testscripts/Windows/DEMO-TEST-FAIL.ps1
  Testscripts/Windows/DEMO-TEST-PASS.ps1
  Testscripts/Windows/DPDK-TESTCASE-DRIVER.ps1
  Testscripts/Windows/DiskHotAddRemove-Parallel.ps1
  Testscripts/Windows/DiskHotAddRemove-Serial.ps1
  Testscripts/Windows/Heartbeat-PausedCritical.ps1
  Testscripts/Windows/HotReSize-VM.ps1
  Testscripts/Windows/LIS-Mount-CD.ps1
  Testscripts/Windows/Max-vCPU.ps1
  Testscripts/Windows/NESTED-HYPERV-NTTTCP-DIFFERENT-L1-PUBLIC-BRIDGE.ps1
  Testscripts/Windows/NESTED-HYPERV-STORAGE-PERF.ps1
  Testscripts/Windows/NESTED-KVM-LAGSCOPE-DIFFERENT-L1-PUBLIC-BRIDGE.ps1
  Testscripts/Windows/NESTED-KVM-NTTTCP-DIFFERENT-L1-PUBLIC-BRIDGE.ps1
  Testscripts/Windows/NESTED-KVM-NTTTCP-PRIVATE-BRIDGE.ps1
  Testscripts/Windows/NESTED-KVM-STORAGE-PERF.ps1
  Testscripts/Windows/PERF-NETWORK-TCP-LATENCY-MULTICONNECTION-LAGSCOPE.ps1
  Testscripts/Windows/PERF-NETWORK-TCP-NETPERF.ps1
  Testscripts/Windows/PERF-NETWORK-TCP-SINGLE-CONNECTION-THROUGHPUT.ps1
  Testscripts/Windows/PERF-NETWORK-THROUGHPUT-MULTICONNECTION-NTTTCP.ps1
  Testscripts/Windows/PERF-NETWORK-UDP-THROUGHPUT-MULTICONNECTION-IPERF3.ps1
  Testscripts/Windows/PERF-STORAGE-MULTIDISK-RAID0-FIO.ps1
  Testscripts/Windows/PERF-STORAGE-OVER-NFS.ps1
  Testscripts/Windows/PERF-SYSCALL-BENCHMARK.ps1
  Testscripts/Windows/STRESSTEST-VERIFY-RESTART.ps1
  Testscripts/Windows/Trigger-FailedNmiInterrupt.ps1
  Testscripts/Windows/Trigger-NmiInterrupt.ps1
  Testscripts/Windows/VERIFY-DPDK-BUILD-AND-TESTPMD-TEST.ps1
  Testscripts/Windows/VERIFY-DPDK-COMPLIANCE.ps1
  Testscripts/Windows/VERIFY-ENABLE-DISABLE-SRIOV-ON-EXISTING-VM.ps1
  Testscripts/Windows/VERIFY-INFINIBAND-MultiVM.ps1
  Testscripts/Windows/VERIFY-NVIDIA-CUDA-DRIVER-INSTALLATION.ps1
  Testscripts/Windows/VERIFY-SRIOV-FAILSAFE-FOR-DPDK.ps1
  Utilities/CopyVHDtoOtherStorageAccount.ps1
  Utilities/Get-SubscriptionUsage.ps1
Labels: enhancement

#283 Hyper-V: 6 VHDx Resize TCs
  Testscripts/Linux/STOR_VHDXResize_PartitionDisk.sh
  Testscripts/Linux/STOR_VHDXResize_ReadWrite.sh
  Testscripts/Windows/STOR-VHDX-RESIZE-BASIC.ps1
  XML/TestCases/FunctionalTests.xml
Labels: New Testcase

#295 Fixed issue in SAS URL file name (Inspect-VHD.ps1)
  JenkinsPipelines/Scripts/InspectVHD.ps1
  Libraries/CommonFunctions.psm1
Labels: bug

#298 Revert "Replaced with ThrowException fn (#290)"
  AutomationManager.ps1
  AzureTestSuite.ps1
  Run-LisaV2.ps1
  Testscripts/Windows/BVT-VERIFY-DEPLOYMENT-PROVISION.ps1
  Testscripts/Windows/BVT-VERIFY-DISKSIZE.ps1
  Testscripts/Windows/BVT-VERIFY-KVP-DAEMON-STATUS.ps1
  Testscripts/Windows/BVT-VERIFY-PRIVATEKEY-AUTHENTICATION.ps1
  Testscripts/Windows/BVT-VERIFY-RESTART.ps1
  Testscripts/Windows/BVT-VERIFY-SHUTDOWN.ps1
  Testscripts/Windows/BVT-VERIFY-SSHD-CONFIG.ps1
  Testscripts/Windows/BVT-VERIFY-VHD-PREREQUISITES.ps1
  Testscripts/Windows/CAPTURE-VHD-BEFORE-TEST.ps1
  Testscripts/Windows/Check-VMBusPanicEvent.ps1
  Testscripts/Windows/DEMO-TEST-Aborted.ps1
  Testscripts/Windows/DEMO-TEST-FAIL.ps1
  Testscripts/Windows/DEMO-TEST-PASS.ps1
  Testscripts/Windows/DPDK-TESTCASE-DRIVER.ps1
  Testscripts/Windows/DiskHotAddRemove-Parallel.ps1
  Testscripts/Windows/DiskHotAddRemove-Serial.ps1
  Testscripts/Windows/Heartbeat-PausedCritical.ps1
  Testscripts/Windows/HotReSize-VM.ps1
  Testscripts/Windows/LIS-Mount-CD.ps1
  Testscripts/Windows/Max-vCPU.ps1
  Testscripts/Windows/NESTED-HYPERV-NTTTCP-DIFFERENT-L1-PUBLIC-BRIDGE.ps1
  Testscripts/Windows/NESTED-HYPERV-STORAGE-PERF.ps1
  Testscripts/Windows/NESTED-KVM-LAGSCOPE-DIFFERENT-L1-PUBLIC-BRIDGE.ps1
  Testscripts/Windows/NESTED-KVM-NTTTCP-DIFFERENT-L1-PUBLIC-BRIDGE.ps1
  Testscripts/Windows/NESTED-KVM-NTTTCP-PRIVATE-BRIDGE.ps1
  Testscripts/Windows/NESTED-KVM-STORAGE-PERF.ps1
  Testscripts/Windows/PERF-NETWORK-TCP-LATENCY-MULTICONNECTION-LAGSCOPE.ps1
  Testscripts/Windows/PERF-NETWORK-TCP-NETPERF.ps1
  Testscripts/Windows/PERF-NETWORK-TCP-SINGLE-CONNECTION-THROUGHPUT.ps1
  Testscripts/Windows/PERF-NETWORK-THROUGHPUT-MULTICONNECTION-NTTTCP.ps1
  Testscripts/Windows/PERF-NETWORK-UDP-THROUGHPUT-MULTICONNECTION-IPERF3.ps1
  Testscripts/Windows/PERF-STORAGE-MULTIDISK-RAID0-FIO.ps1
  Testscripts/Windows/PERF-STORAGE-OVER-NFS.ps1
  Testscripts/Windows/PERF-SYSCALL-BENCHMARK.ps1
  Testscripts/Windows/STRESSTEST-VERIFY-RESTART.ps1
  Testscripts/Windows/Trigger-FailedNmiInterrupt.ps1
  Testscripts/Windows/Trigger-NmiInterrupt.ps1
  Testscripts/Windows/VERIFY-DPDK-BUILD-AND-TESTPMD-TEST.ps1
  Testscripts/Windows/VERIFY-DPDK-COMPLIANCE.ps1
  Testscripts/Windows/VERIFY-ENABLE-DISABLE-SRIOV-ON-EXISTING-VM.ps1
  Testscripts/Windows/VERIFY-INFINIBAND-MultiVM.ps1
  Testscripts/Windows/VERIFY-NVIDIA-CUDA-DRIVER-INSTALLATION.ps1
  Testscripts/Windows/VERIFY-SRIOV-FAILSAFE-FOR-DPDK.ps1
  Utilities/CopyVHDtoOtherStorageAccount.ps1
  Utilities/Get-SubscriptionUsage.ps1
Labels: LISAv2 Broken

#250 Hyper-V: Dynamic Memory test cases
  Libraries/HyperV.psm1
  Testscripts/Linux/DM_HotAdd_Verify_udev.sh
  Testscripts/Windows/DM-CONFIGURE-MEMORY.ps1
  XML/TestCases/FunctionalTests.xml
  XML/TestCases/StressTests.xml
Labels: New Testcase

#286 Support CLEAROS run BVT and Performance
  Testscripts/Linux/BVT-CORE-TIME-CLOCKEVENT.sh
  Testscripts/Linux/BVT-CORE-TIME-CLOCKSOURCE.sh
  Testscripts/Linux/BVT-SWAP-CHECK.py
  Testscripts/Linux/BVT-VERIFY-UUID-FSTAB.py
  Testscripts/Linux/BVT-VERIFY-VERBOSE-ENABLED-LOGS.py
  Testscripts/Linux/CreateRaid.sh
  Testscripts/Linux/azuremodules.py
  Testscripts/Linux/enableRoot.sh
  Testscripts/Linux/perf_fio.sh
  Testscripts/Linux/utils.sh
  Testscripts/Windows/PERF-NETWORK-TCP-SINGLE-CONNECTION-THROUGHPUT.ps1
Labels: enhancement

#291 Genericize dpdk
  Testscripts/Linux/dpdk-testFWD.sh
  Testscripts/Linux/dpdk-testFailsafe.sh
  Testscripts/Linux/dpdk-testPMD.sh
  Testscripts/Linux/dpdkSetupAndRunTest.sh
  Testscripts/Linux/dpdkUtils.sh
  Testscripts/Linux/utils.sh
  Testscripts/Windows/DPDK-TESTCASE-DRIVER.ps1
  Testscripts/Windows/dpdk-testFWD.ps1
  Testscripts/Windows/dpdk-testFailsafe.ps1
  Testscripts/Windows/dpdk-testPMD.ps1
  XML/Other/testfwd_pps_lowerbound.xml
  XML/Other/testpmd_pps_lowerbound.xml
  XML/TestCases/FunctionalTests-DPDK.xml
  XML/TestCases/PerformanceTests-DPDK.xml
  XML/VMConfigurations/PerformanceTestsConfigurations.xml
Labels: New Testcase

#308 Hide the warning message from PS Module Import
  JenkinsPipelines/Scripts/DeletePartnerFiles.ps1
  JenkinsPipelines/Scripts/DetectTestRegions.ps1
  JenkinsPipelines/Scripts/GetPartnerStorageUsage.ps1
  JenkinsPipelines/Scripts/InspectCustomKernel.ps1
  JenkinsPipelines/Scripts/InspectVHD.ps1
  JenkinsPipelines/Scripts/JenkinsTestSelectionMenuGenerator.ps1
  JenkinsPipelines/Scripts/ReceivePartnerFiles.ps1
  JenkinsPipelines/Scripts/UpdateAzureRegionAndVMSizes.ps1
  JenkinsPipelines/Scripts/UpdatePublisherImages.ps1
  Run-LisaV2.ps1
  Utilities/AddAzureRmAccountFromSecretsFile.ps1
  Utilities/AnalyseAllResults.ps1
  Utilities/CopyVHDtoOtherStorageAccount.ps1
  Utilities/Get-AzureVMs.ps1
  Utilities/Get-SubscriptionUsage.ps1
  Utilities/Get-SubscriptionUsageTopVMs.ps1
  Utilities/ManageTestStorageAccounts.ps1
  Utilities/UpdateGlobalConfigurationFromXmlSecrets.ps1
  Utilities/UploadFilesToStorageAccount.ps1
  Utilities/UploadVHDtoAzureStorage.ps1
Labels: enhancement

#311 Added default tags to Azure Resource Group
  Libraries/Azure.psm1
  Libraries/CommonFunctions.psm1
Labels: enhancement

#313 Hyper-V: Added 24 Storage tests
  Libraries/Test-Framework.psm1
  Testscripts/Linux/STOR-Large-CopyFile.sh
  Testscripts/Linux/STORAGE-HotRemove.sh
  Testscripts/Linux/STORAGE-LargeDisk.sh
  Testscripts/Windows/AddHardDisk.ps1
  Testscripts/Windows/CLEANUP-DiffDiskGrowth.ps1
  Testscripts/Windows/RemoveHardDisk.ps1
  Testscripts/Windows/RemoveVhdxHardDisk.ps1
  Testscripts/Windows/SETUP-DiffDiskGrowth.ps1
  Testscripts/Windows/SETUP-RemoveIsoFromDvd.ps1
  Testscripts/Windows/STORAGE-DiffDiskGrowth.ps1
  Testscripts/Windows/STORAGE-HotAdd.ps1
  Testscripts/Windows/STORAGE-HotAddVhdx.ps1
  Testscripts/Windows/STORAGE-HotRemove.ps1
  Testscripts/Windows/STORAGE-HotRemoveVhdx.ps1
  Testscripts/Windows/STORAGE-HotUnplug.ps1
  XML/TestCases/FunctionalTests.xml
Labels: New Testcase

#303 Hyper-V: Added 8 VHDx Resize tests
  Testscripts/Linux/STOR_VHDXResize_PartitionDisk.sh
  Testscripts/Linux/STOR_VHDXResize_PartitionDiskOver2TB.sh
  Testscripts/Windows/STOR-VHDX-RESIZE-BASIC.ps1
  Testscripts/Windows/STOR-VHDX-RESIZE-GROWSHRINK.ps1
  XML/TestCases/FunctionalTests.xml
Labels: New Testcase

#293 Hyper-V: Added 2 Secure Boot tests
  Testscripts/Linux/utils.sh
  Testscripts/Windows/SECUREBOOT.ps1
  Testscripts/Windows/SET-SECUREBOOT.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests.xml
Labels: New Testcase

#234 Hyper-V: Added 9 Runtime Memory Resize tests
  Libraries/CommonFunctions.psm1
  Testscripts/Windows/RUNTIME-MEM-CONFIGURE.ps1
  Testscripts/Windows/RUNTIME-MEM-HOTADD.ps1
  Testscripts/Windows/RUNTIME_MEM_HOTADD_CHUNKS.ps1
  Testscripts/Windows/RUNTIME_MEM_HOTADD_REBOOT.ps1
  Testscripts/Windows/RUNTIME_MEM_MULTIPLEADDREMOVE.ps1
  Testscripts/Windows/RUNTIME_MEM_STRESSHOTREMOVE.ps1
  XML/TestCases/FunctionalTests.xml
Labels: New Testcase

#318 Hyper-V: Added 24 Storage tests
  Libraries/Test-Framework.psm1
  Testscripts/Linux/STOR-Large-CopyFile.sh
  Testscripts/Linux/STORAGE-HotRemove.sh
  Testscripts/Linux/STORAGE-LargeDisk.sh
  Testscripts/Windows/AddHardDisk.ps1
  Testscripts/Windows/CLEANUP-DiffDiskGrowth.ps1
  Testscripts/Windows/RemoveHardDisk.ps1
  Testscripts/Windows/RemoveVhdxHardDisk.ps1
  Testscripts/Windows/SETUP-DiffDiskGrowth.ps1
  Testscripts/Windows/SETUP-RemoveIsoFromDvd.ps1
  Testscripts/Windows/STORAGE-DiffDiskGrowth.ps1
  Testscripts/Windows/STORAGE-HotAdd.ps1
  Testscripts/Windows/STORAGE-HotAddVhdx.ps1
  Testscripts/Windows/STORAGE-HotRemove.ps1
  Testscripts/Windows/STORAGE-HotRemoveVhdx.ps1
  Testscripts/Windows/STORAGE-HotUnplug.ps1
  XML/TestCases/FunctionalTests.xml
Labels: New Testcase

#312 Set up CI with Azure Pipelines
  azure-pipelines.yml
Labels: enhancement

#307 Hyper-V: Added 6 Production checkpoint tests
  Libraries/CommonFunctions.psm1
  Testscripts/Linux/STOR_VSS_ISCSI_PartitionDisks.sh
  Testscripts/Linux/STOR_VSS_StopNetwork.sh
  Testscripts/Linux/utils.sh
  Testscripts/Windows/PRODUCTION-CHECKPOINT-3CHAIN-VHD.ps1
  Testscripts/Windows/PRODUCTION-CHECKPOINT-FAILBACK.ps1
  Testscripts/Windows/PRODUCTION-CHECKPOINT-ISO-NONETWORK.ps1
  Testscripts/Windows/PRODUCTION-CHECKPOINT-PARTITION.ps1
  Testscripts/Windows/PRODUCTION-CHECKPOINT-iSCSI.ps1
  Testscripts/Windows/PRODUCTION-CHECKPOINT.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests.xml
Labels: New Testcase

#315 Hyper-V: Added 2 VHDx Resize tests
  Testscripts/Linux/STOR_VHDXResize_GrowFSAfterResize.sh
  Testscripts/Windows/STOR-VHDX-RESIZE-GROWFS.ps1
  XML/TestCases/FunctionalTests.xml
Labels: New Testcase

#289 utils.sh: Set LIS_HOME to location where files copied to
  Testscripts/Linux/utils.sh
Labels: enhancement

#310 Hyper-V : Added 4 Network Gen2 VM tests
  Libraries/CommonFunctions.psm1
  Testscripts/Linux/NET-Verify-Boot-NoNIC.sh
  Testscripts/Linux/NET-Verify-HotAdd-MultiNIC.sh
  Testscripts/Windows/NET-Boot-NoNIC-HotAdd-NIC.ps1
  Testscripts/Windows/NET-HotAdd-MultiNIC.ps1
  Testscripts/Windows/NET-HotAddRemove-Max-NIC.ps1
  XML/TestCases/FunctionalTests.xml
Labels: New Testcase

#333 fixed a typo
  Run-LisaV2.ps1
Labels: bug

#319 Fixed CreationTime -- Simplified Tag/VmSize/VmLocation. CreationTime can also be read from VM Tag.
  Utilities/Get-AzureVMs.ps1
Labels: bug

#322 azure,hyperv: Added 10 functional SR-IOV test cases
  Testscripts/Linux/SR-IOV-Utils.sh
  Testscripts/Linux/SRIOV-DisableVF.sh
  Testscripts/Linux/SRIOV-Iperf-Stress.sh
  Testscripts/Linux/SRIOV-ModuleReload.sh
  Testscripts/Linux/SRIOV-Verify-lspci.sh
  Testscripts/Linux/SRIOV-VerifyVF-Connection.sh
  Testscripts/Linux/sriov-lspci.sh
  Testscripts/Linux/utils.sh
  Testscripts/Linux/verify-ifdown-ifup-eth0-rmmod-modprobe-hv-netvsc.sh
  Testscripts/Windows/SETUP-NET-Add-NIC.ps1
  Testscripts/Windows/SETUP-SR-IOV-Configure.ps1
  Testscripts/Windows/SRIOV-RUN-COMMON-TEST.ps1
  XML/TestCases/FunctionalTests-SRIOV.xml
  XML/VMConfigurations/FunctionalTestsConfigurations.xml
Labels: New Testcase

#320 Support performance testing against CoreOS
  Libraries/CommonFunctions.psm1
  Libraries/Test-Framework.psm1
  Testscripts/Linux/BVT-CORE-TIME-CLOCKSOURCE.sh
  Testscripts/Linux/enableRoot.sh
  Testscripts/Linux/fio_jason_parser.sh
  Testscripts/Linux/perf_fio.sh
  Testscripts/Linux/perf_iperf3.sh
  Testscripts/Linux/perf_lagscope.sh
  Testscripts/Linux/perf_netperf.sh
  Testscripts/Linux/perf_ntttcp.sh
  Testscripts/Linux/utils.sh
  Testscripts/Windows/NESTED-HYPERV-STORAGE-PERF.ps1
  Testscripts/Windows/NESTED-KVM-STORAGE-PERF.ps1
  Testscripts/Windows/PERF-STORAGE-MULTIDISK-RAID0-FIO.ps1
  Testscripts/Windows/PERF-STORAGE-OVER-NFS.ps1
Labels: enhancement

#334 Fix : lisav2 fails when the ssh host key is not trusted #330
  Libraries/CommonFunctions.psm1
Labels: enhancement

#317 Added new Secureboot testcase
  Libraries/CommonFunctions.psm1
  Testscripts/Windows/CLEANUP-Backup-DISK.ps1
  Testscripts/Windows/SETUP-Backup-DISK.ps1
  Testscripts/Windows/STOR-VSS-BACKUP-RESTORE-PARTITION.ps1
  XML/TestCases/FunctionalTests.xml
Labels: New Testcase

#323 hyper-v : Fix ETHTOOL-CHECK-STATISTICS
  Testscripts/Linux/NET-Ethtool-Check-Statistics.sh
Labels: bug

#292 Azure: Added support to ephemeral OS Disk (Preview)
  Libraries/Azure.psm1
  XML/TestCases/SmokeTests.xml
Labels: enhancement

#331 Small fix in printing download location
  Libraries/Framework.psm1
Labels: bug

#335 customKernelInstall: apt-update & install binutils required for kernel install
  Testscripts/Linux/customKernelInstall.sh
Labels: enhancement

#340 lisav2: Don't copy temp files on workspace change
  Run-LisaV2.ps1
Labels: enhancement

#324 LISAv2: remove parameters 'UpdateGlobalConfigurationFromSecretsFile a…
  Run-LisaV2.ps1
Labels: enhancement

#341 azure,hyperv: Fixed cpio unpacking for initrd TC
  Testscripts/Linux/CORE-InitrdModulesCheck.sh
Labels: bug
