Repository LIS/LISAv2, pull requests merged in 2018-06, with the labels that each got.

#47 Fixing issue : Wrong WALA file names
  JenkinsPipelines/Scripts/GetSubscriptionUsage.ps1
  JenkinsPipelines/Scripts/SubscriptionUsageTopVMs.ps1
  Testscripts/Linux/WALA-PROCESS-CHECK.py
  Testscripts/Linux/WALA-RESOURCE-DISK-FILESYSTEM-CHECK.py
  Testscripts/Linux/WALA-VERIFY-FIREWALL-STATUS.py
  Testscripts/Linux/WALA-VERIFY-HOSTNAME.py
  Testscripts/Linux/WALA-VERIFY-MNT-RESOURCE-WRITABLE.py
  Testscripts/Linux/WALA-VERSION-CHECK.py
  Testscripts/Windows/WALA-PROCESS-CHECK.ps1
  Testscripts/Windows/WALA-RESOURCE-DISK-FILESYSTEM-CHECK.ps1
  Testscripts/Windows/WALA-VERIFY-FIREWALL-STATUS.ps1
  Testscripts/Windows/WALA-VERIFY-HOSTNAME.ps1
  Testscripts/Windows/WALA-VERIFY-MNT-RESOURCE-README.ps1
  Testscripts/Windows/WALA-VERIFY-MNT-RESOURCE-WRITABLE.ps1
  Testscripts/Windows/WALA-VERSION-CHECK.ps1
  XML/TestCases/FunctionalTests-WALA.xml
Labels: bug

#49 Fixed issue with custom kernel upload from remote launch script
  JenkinsPipelines/Scripts/ReceivePartnerFiles.ps1
  Utilities/LaunchTestPipelineRemotely.sh
Labels: bug

#51 Added support to launch test jobs without re-uploading files
  .gitignore
  JenkinsPipelines/Scripts/InspectCustomKernel.ps1
  JenkinsPipelines/Scripts/InspectVHD.ps1
  JenkinsPipelines/Scripts/ReceivePartnerFiles.ps1
  Utilities/AnalyseAllResults.ps1
  Utilities/LaunchTestPipelineRemotely.sh
  Utilities/TestParameters.sh
  XML/TestCases/SmokeTests.xml
Labels: enhancement

#58 New tests for ifup - ifdown eth0 + fixes for BVT tests
  Libraries/CommonFunctions.psm1
  RunTests.ps1
  Testscripts/Linux/verify-ifdown-ifup-eth0-rmmod-modprobe-hv-netvsc.sh
  Testscripts/Windows/BVT-VERIFY-SHUTDOWN.ps1
  Testscripts/Windows/VERIFY-TEST-SCRIPT-IN-LINUX-GUEST.ps1
  Utilities/UpdateGlobalConfigurationFromXmlSecrets.ps1
  XML/Other/ignorable-boot-errors.xml
  XML/Other/ignorable-walalog-errors.xml
  XML/TestCases/BVT.xml
  XML/TestCases/FunctionalTests-SRIOV.xml
  XML/TestCases/FunctionalTests-Synthetic.xml
  XML/TestCases/PerformanceTests.xml
Labels: New Testcase, bug, enhancement

#59 Fixed : Internal IP was not being collected from PrimaryNIC sometimes.
  Libraries/Azure.psm1
  Libraries/CommonFunctions.psm1
Labels: bug

#69 Juhlee/doc add azure test
  Documents/How-to-use.md
  XML/Other/ignorable-boot-errors.xml
  XML/Other/ignorable-walalog-errors.xml
  XML/RegionAndStorageAccounts.xml
  XML/TestCases/BVT.xml
  XML/TestCases/CommunityTests.xml
  XML/TestCases/FunctionalTests-GPU.xml
  XML/TestCases/FunctionalTests-SRIOV.xml
  XML/TestCases/FunctionalTests-Synthetic.xml
  XML/TestCases/NestedKvmTests.xml
  XML/TestCases/Other.xml
  XML/TestCases/PerformanceTests.xml
  XML/TestCases/SmokeTests.xml
Labels: enhancement

#80 Bug fixes
  JenkinsPipelines/Scripts/DetectTestRegions.ps1
  XML/RegionAndStorageAccounts.xml
Labels: bug
