Repository LIS/LISAv2, pull requests merged in 2019-02, with the labels that each got.

#667 Added WSL as a new supported platform
  LISAv2-Framework.psm1
  Libraries/TestHelpers.psm1
  Libraries/TestLogs.psm1
  README.md
  Run-LisaV2.ps1
  TestControllers/WSLController.psm1
  TestProviders/WSLProvider.psm1
  XML/GlobalConfigurations.xml
  XML/TestCases/BVT.xml
  XML/TestCases/PerformanceTests.xml
Labels: New Feature

#691 Revert change for remove-Variable
  LISAv2-Framework.psm1
Labels: bug

#693 FILESYSTEM-TESTS: Consolidate xfstests test cases
  Testscripts/Linux/perf_xfstesting.sh
  Testscripts/Linux/xfstesting.sh
  Testscripts/Linux/xfstests-config.config
  Testscripts/Windows/FILE-SYSTEM-VERIFICATION-TESTS.ps1
  XML/TestCases/CommunityTests.xml
  XML/TestCases/FunctionalTests-NVME.xml
Labels: CodeRefactoring, New Feature, New Testcase

#683 hyperv: reuse failed test case vm
  Libraries/HyperV.psm1
  TestControllers/TestController.psm1
  TestProviders/HyperVProvider.psm1
  TestProviders/TestProvider.psm1
Labels: enhancement

#681 Add new test case for kernel config verify
  Testscripts/Linux/kernel_config_verify_test.sh
  Testscripts/Windows/KERNEL-CONFIG-VERIFY-TEST.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests-OL.xml
Labels: New Testcase

#700 Azure: wait 10s between resource group creation retry
  Libraries/Azure.psm1
Labels: bug

#699 Framework : Fixed junit report - testsuite name and class
  TestControllers/TestController.psm1
Labels: enhancement

#679 Added script to remove old Azure VMs
  Utilities/Remove-OldAzureVMs.ps1
Labels: Utility

#695 Move KVP-ADD/MODIFY/REMOVE-KEY-VALUES under KVP-VALUES-OPERATIONS
  TestProviders/HyperVProvider.psm1
  Testscripts/Linux/KVP-AddKeyValues.sh
  Testscripts/Windows/KVP-AddKeyValues.ps1
  Testscripts/Windows/KVP-KEY-VALUES-OPERATIONS.ps1
  Testscripts/Windows/KVP-ModifyKeyValues.ps1
  Testscripts/Windows/KVP-RemoveKeyValues.ps1
  XML/TestCases/FunctionalTests-KVP.xml
Labels: CodeRefactoring

#701 TIMESYNC-VDSO: update real-time threshold values
  Testscripts/Windows/Timesync-VDSO.ps1
Labels: bug

#698 hyperv: run test script on non-dependency vms
  Libraries/CommonFunctions.psm1
  TestProviders/HyperVProvider.psm1
Labels: bug

#705 FILESYSTEM-TESTS: Added SLES support
  Testscripts/Linux/xfstesting.sh
Labels: enhancement

#707 Add new DYNAMIC-MEMORY-TOP-LOAD-AVERAGE testcase
  Testscripts/Linux/DM_Top_Load_Average.sh
  XML/TestCases/FunctionalTests-DynamicMemory.xml
Labels: New Testcase

#708 IB: Various fixes
  Testscripts/Linux/SetupRDMA.sh
  Testscripts/Linux/TestRDMA_MultiVM.sh
Labels: bug

#696 Added LIS Deploy Scenario Test cases
  Testscripts/Windows/LIS-INSTALL-SCENARIOS.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/BVT.xml
  XML/TestCases/LIS-Tests.xml
Labels: New Testcase

#712 IB: Various fixes
  Libraries/Framework-Azure.psm1
  Testscripts/Linux/SetupRDMA.sh
  Testscripts/Linux/TestRDMA_MultiVM.sh
  XML/Other/ReplaceableTestParameters.xml
Labels: bug, enhancement

#706 Framework: Implement skipped test case state
  LISAv2-Framework.psm1
  Libraries/CommonFunctions.psm1
  Libraries/TestLogs.psm1
  Libraries/TestReport.psm1
  TestControllers/TestController.psm1
  Testscripts/Linux/LIS-VERSION-CHECK.sh
Labels: enhancement

#688 Code Coverage: Added code coverage feature
  LISAv2-Framework.psm1
  Libraries/CommonFunctions.psm1
  Libraries/TestLogs.psm1
  Run-LisaV2.ps1
  TestControllers/TestController.psm1
  Testscripts/Linux/build_gcov_kernel.sh
  Testscripts/Linux/collect_gcov_data.sh
  Testscripts/Linux/generate_gcov.sh
  Testscripts/Linux/generate_gcov_report.sh
  Testscripts/Windows/Build-GcovKernel.ps1
  Testscripts/Windows/Get-GcovReport.ps1
  Utilities/CodeCoverage/Upload-Report.ps1
  Utilities/CodeCoverage/create_coverage_file.py
  Utilities/Launch-GcovTest.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/Other.xml
Labels: New Feature

#715 Framework: Upstream stable kernel support
  Libraries/CommonFunctions.psm1
  Testscripts/Linux/customKernelInstall.sh
Labels: enhancement

#713 Print git branch name and commit Id in LISAv2 log
  LISAv2-Framework.psm1
Labels: enhancement

#720 OL: Add support for multiple provider.
  LISAv2-Framework.psm1
  Libraries/TestHelpers.psm1
  Libraries/TestLogs.psm1
  Run-LisaV2.ps1
  TestControllers/OLController.psm1
  TestProviders/OLQProvider.psm1
  XML/TestCases/BVT.xml
Labels: New Feature

#687 Add utility script to create service principal
  Utilities/CreateServicePrincipal.ps1
Labels: New Feature

#722 Fix for customKernelInstall.sh
  Testscripts/Linux/customKernelInstall.sh
Labels: bug

#725 AddVhdxHardDisk.ps1: fix for non-cluster env
  Testscripts/Windows/AddVhdxHardDisk.ps1
Labels: bug

#724 Add 3 new DYNAMIC-MEMORY testcases
  Testscripts/Windows/DM-HOTADD-EATMEMORY.ps1
  Testscripts/Windows/DM-REMOVE-THEN-PRESSURE.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests-DynamicMemory.xml
Labels: New Testcase

#727 AddVhdxHardDisk.ps1: Addition fix for PR #725
  Testscripts/Windows/AddVhdxHardDisk.ps1
Labels: bug

#730 HyperV: Fix BVT-CORE-RELOAD-MODULES.ps1
  Testscripts/Windows/BVT-CORE-RELOAD-MODULES.ps1
Labels: bug

#739 Fix the value of the test case results
  Testscripts/Windows/BVT-NET-IFUP-IFDOWN.ps1
  Testscripts/Windows/BVT-VERIFY-SSHD-CONFIG.ps1
  Testscripts/Windows/BVT-VERIFY-VHD-PREREQUISITES.ps1
Labels: bug

#742 Fixed: LISAv2 was checking for IP in infinite loop after VM checkpoint
  Libraries/HyperV.psm1
Labels: bug

#697 Framework: New parameter: ResourceCleanup (Replaces 2 parameters)
  LISAv2-Framework.psm1
  Libraries/Azure.psm1
  Run-LisaV2.ps1
  TestControllers/TestController.psm1
Labels: P1, enhancement

#744 Storage: Fix controller and disk count issues
  XML/TestCases/FunctionalTests-Storage.xml
Labels: bug

#737 Rename CustomParameters into CustomTestParameters, enable CustomParameters for the parameters.
  JenkinsPipelines/Run-Boot-Stress-Tests.groovy
  LISAv2-Framework.psm1
  Libraries/Azure.psm1
  Libraries/CommonFunctions.psm1
  Run-LisaV2.ps1
  TestControllers/AzureController.psm1
  TestControllers/TestController.psm1
  Utilities/Launch-GcovTest.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestParameters.xml
Labels: enhancement

#714 Azure: Added Resource Group usage check in Validate-SubscriptionUsage()
  Libraries/Azure.psm1
Labels: PR-Verified, enhancement

#741 Utilities: Added script to remove LISAv2 old files.
  Utilities/Remove-LISAv2OrphanFiles.ps1
Labels: P1, enhancement

#743 LISAv2 New Feature: "Support for excluding the tests"
  LISAv2-Framework.psm1
  Libraries/CommonFunctions.psm1
  Run-LisaV2.ps1
  TestControllers/TestController.psm1
  XML/TestParameters.xml
Labels: New Feature, PR-Verified, enhancement

#694 HyperV: Added support to download VHDs from web URL (-OsVHD <web url>)
  .gitignore
  Libraries/CommonFunctions.psm1
  Libraries/HyperV.psm1
  README.md
  TestProviders/HyperVProvider.psm1
Labels: P2, PR-Verified, enhancement

#747 Azure: .\XML\RegionAndStorageAccounts.xml will be updated using secret file.
  TestControllers/TestController.psm1
Labels: PR-Verified, enhancement

#752 Rename the global variable "IsWindows" to "IsWindowsImage".
  Documents/How-to-use.md
  Libraries/Azure.psm1
  Libraries/CommonFunctions.psm1
  Libraries/HyperV.psm1
  TestControllers/TestController.psm1
  Testscripts/Windows/NESTED-HYPERV-NTTTCP-DIFFERENT-L1-NAT.ps1
  Testscripts/Windows/NESTED-HYPERV-NTTTCP-DIFFERENT-L1-PUBLIC-BRIDGE.ps1
Labels: PR-Verified, bug

#745 Re-design VM size series
  Libraries/Azure.psm1
Labels: enhancement

#764 Rename global ResultFailed/ResultPassed to ResultFail/ResultPass
  Documents/How-to-use.md
  Libraries/TestLogs.psm1
  Libraries/TestReport.psm1
  TestControllers/TestController.psm1
Labels: PR-Verified, bug

#761 Enable nested virtualization in setup script, instead of in framework…
  Libraries/HyperV.psm1
  Testscripts/Windows/SETUP-Enable-NestedVirtualization.ps1
  XML/TestCases/NestedVmTests.xml
Labels: PR-Verified, enhancement

#762 Cleanup testcase xmls
  XML/TestCases/FunctionalTests-DynamicMemory.xml
  XML/TestCases/FunctionalTests-LiveMigration.xml
  XML/TestCases/FunctionalTests-NVME.xml
  XML/TestCases/FunctionalTests-OL.xml
  XML/TestCases/NestedVmTests.xml
  XML/TestCases/PerformanceTests.xml
  XML/TestCases/StressTests.xml
Labels: CodeRefactoring

#746 New TC: Added Infiniband TestCases
  Testscripts/Linux/SetupRDMA.sh
  Testscripts/Linux/TestRDMA_MultiVM.sh
  Testscripts/Windows/VERIFY-INFINIBAND-MultiVM.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests-InfiniBand.xml
  XML/VMConfigurations/MultiVMs.xml
Labels: CodeRefactoring, PR-under-test, enhancement

#769 Fix: Replaced LogErr with Write-LogErr in SETUP-SRI-IOV-Configure
  Testscripts/Windows/SETUP-SR-IOV-Configure.ps1
Labels: P0, bug

#770 Renamed IB test cases by omitting VERIFY-
  XML/TestCases/FunctionalTests-InfiniBand.xml
Labels: CodeRefactoring, P2

#758 Functional Tests GPU: automation refresh
  Libraries/Azure.psm1
  Libraries/TestHelpers.psm1
  Testscripts/Linux/InstallCUDADrivers.sh
  Testscripts/Linux/KDUMP-Results.sh
  Testscripts/Linux/install_CUDA_drivers.sh
  Testscripts/Linux/utils.sh
  Testscripts/Windows/FILE-SYSTEM-VERIFICATION-TESTS.ps1
  Testscripts/Windows/NVIDIA-CUDA-DRIVER-INSTALLATION.ps1
  Testscripts/Windows/VERIFY-NVIDIA-CUDA-DRIVER-INSTALLATION.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests-GPU.xml
Labels: CodeRefactoring, P0

#748 Fix: Replaceable test parameters can also replace test case names
  TestControllers/TestController.psm1
  XML/Other/ReplaceableTestParameters.xml
Labels: PR-Verified, bug

#774 Fix escaped outputs in DYNAMIC/RUNTIME Memory
  Testscripts/Windows/DM-HOTADD-STRESS-APP.ps1
  Testscripts/Windows/DM-MAXMEMHONOR.ps1
  Testscripts/Windows/DM-MINMEMHONOR.ps1
  Testscripts/Windows/DM-SAVE-RESTORE.ps1
  Testscripts/Windows/DM_CleanShutdown.ps1
  Testscripts/Windows/DM_HIGH-PRIORITY.ps1
  Testscripts/Windows/DM_HotAddRemove.ps1
  Testscripts/Windows/DM_REMOVE-UNDER-PRESSURE.ps1
  Testscripts/Windows/DM_StartupLowCompete.ps1
  Testscripts/Windows/RUNTIME-MEM-HOTADD.ps1
  Testscripts/Windows/RUNTIME_MEM_HOTADD_CHUNKS.ps1
  Testscripts/Windows/RUNTIME_MEM_MULTIPLEADDREMOVE.ps1
  Testscripts/Windows/RUNTIME_MEM_STRESSHOTREMOVE.ps1
Labels: PR-under-test, bug

#771 GetDistro: fix for redhat/centos 7.6 detection
  Testscripts/Linux/utils.sh
Labels: P0, PR-Verified, bug

#779 IB: Replaced default VM size to Standard_HB60rs
  XML/TestCases/FunctionalTests-InfiniBand.xml
Labels: P1, RDMA

#778 CUDA_drivers: Install LIS RPMs on centos/redhat
  Testscripts/Linux/install_CUDA_drivers.sh
  Testscripts/Windows/NET-Boot-NoNIC-HotAdd-NIC.ps1
  Testscripts/Windows/NVIDIA-CUDA-DRIVER-INSTALLATION.ps1
Labels: PR-Verified, enhancement

#780 Print out Blob storage location update
  Libraries/TestHelpers.psm1
Labels: bug

#782 Fixed NET Gen2 testcases to return skipped instead of aborted
  Testscripts/Windows/NET-Boot-NoNIC-HotAdd-NIC.ps1
  Testscripts/Windows/NET-HotAdd-MultiNIC.ps1
  Testscripts/Windows/NET-HotAddRemove-Max-NIC.ps1
Labels: bug

#785 HyperV.psm1: Added the hostname in /etc/hosts
  Libraries/HyperV.psm1
Labels: bug

#784 CUDA_drivers: Added check for LIS RPMs
  Testscripts/Linux/install_CUDA_drivers.sh
  Testscripts/Windows/NVIDIA-CUDA-DRIVER-INSTALLATION.ps1
Labels: bug, enhancement

#768 HyperV: Added RHEL registration
  Libraries/CommonFunctions.psm1
  Libraries/TestHelpers.psm1
  TestProviders/HyperVProvider.psm1
  Testscripts/Linux/Register-Redhat.sh
Labels: P0, PR-Verified, enhancement

#783 Remove workaround for Ubuntu Bionic.
  Testscripts/Windows/CAPTURE-VHD-BEFORE-TEST.ps1
Labels: DO-NOT-MERGE, P0, PR-Verified, bug

#790 Replace usages of tools folder to be case sensitive in powershell files
  Libraries/TestHelpers.psm1
Labels: P0, bug

#765 Add the new test case of hot-resize vm
  Testscripts/Windows/HotReSize-VM.ps1
  Testscripts/Windows/VM-HOT-RESIZE.ps1
  XML/TestCases/FunctionalTests.xml
Labels: New Testcase, P1

#773 OLQ: Added LTP and fixed OLQ deployment
  TestProviders/OLQProvider.psm1
  Testscripts/Linux/Linux-Test-Project-Tests.sh
  Testscripts/Linux/deploy_ol_vm.sh
  Testscripts/Windows/OL-PackageCheck.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/CommunityTests.xml
  XML/TestCases/FunctionalTests-OL.xml
Labels: New Testcase, P1, bug

#789 Hyperv : Fix issues in Storage test cases
  Testscripts/Linux/STOR-Lis-Disk.sh
  Testscripts/Windows/STOR-VHDX-RESIZE-GROWSHRINK.ps1
  Testscripts/Windows/STORAGE-HotAdd.ps1
  XML/TestCases/FunctionalTests-Storage.xml
Labels: P0, bug

#795 NETWORK: Various fixes for Hyper-V
  Testscripts/Linux/NET-Copy-Large-File.sh
  Testscripts/Linux/NET-Corruption.sh
  Testscripts/Linux/NET-Max-NICs.sh
  Testscripts/Linux/NET-Operstate.sh
  Testscripts/Linux/NET-Test-Legacy.sh
  Testscripts/Linux/NET-Test-Network.sh
  Testscripts/Linux/NET-Test-Promiscuous.sh
  Testscripts/Linux/NET-Verify-Boot-NoNIC.sh
  Testscripts/Linux/NET-Verify-HotAdd-MultiNIC.sh
  Testscripts/Linux/utils.sh
  Testscripts/Windows/NET-File-Copy-SCP.ps1
  Testscripts/Windows/NET-Test-Private-Network.ps1
  Testscripts/Windows/SETUP-NET-Switch-NIC.ps1
Labels: bug

#799 Capitalize the path per PR 790
  Libraries/TestHelpers.psm1
Labels: bug

#797 Disable automatic checkpoints on Hyper-V VMs
  Libraries/HyperV.psm1
Labels: enhancement

#803 Fix issue when return value contains more than 1 match.
  Libraries/TestLogs.psm1
Labels: bug

#810 STRESS-Web.ps1: Fix distribution check
  Testscripts/Windows/STRESS-Web.ps1
Labels: bug

#812 HyperV: fix secure boot set on other host
  Libraries/HyperV.psm1
Labels: bug

#811 Testscripts: Various fixes in bash scripts
  Testscripts/Linux/CORE-CPUVerifyOnline.sh
  Testscripts/Linux/KVP-BasicChecks.sh
  Testscripts/Linux/NET-Copy-Large-File.sh
  Testscripts/Linux/STOR-Large-CopyFile.sh
  Testscripts/Linux/STORAGE-HotRemove.sh
  Testscripts/Linux/STORAGE-LargeDisk.sh
  Testscripts/Linux/Sysbench.sh
  Testscripts/Linux/utils.sh
Labels: bug

#809 HyperV: Abort TC if the server is not in a cluster
  Libraries/HyperV.psm1
Labels: P0, PR-under-test, bug

#791 Create PULL_REQUEST_TEMPLATE.md
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#805 Fix for install package against sles.
  Testscripts/Linux/SetupRDMA.sh
Labels: bug

#806 INITRD-MODULES-CHECK: Fixed SLES support
  Testscripts/Linux/CORE-InitrdModulesCheck.sh
Labels: PR-Verified, enhancement

#814 Add entry for Oracle-Linux of performance test cases.
  Testscripts/Linux/utils.sh
Labels: bug

#816 xfstests: Removed mount options for XFS FS
  XML/TestCases/CommunityTests.xml
  XML/TestCases/FunctionalTests-NVME.xml
Labels: enhancement

#817 HyperV: Fix: join-path fails in case of mismatched drives between LISAv2 executor and Server under test
  Libraries/HyperV.psm1
Labels: PR-Verified, enhancement

#804 Upload results to database in framework level
  Libraries/Database.psm1
  Libraries/TestHelpers.psm1
  TestControllers/TestController.psm1
  Testscripts/Windows/DPDK-TESTCASE-DRIVER.ps1
  Testscripts/Windows/PERF-NETWORK-TCP-LATENCY-MULTICONNECTION-LAGSCOPE.ps1
  Testscripts/Windows/VERIFY-DPDK-BUILD-AND-TESTPMD-TEST.ps1
Labels: CodeRefactoring

#820 Remove extra character
  XML/TestCases/FunctionalTests.xml
Labels: bug

#813 Fix download file issue against clearos
  Libraries/CommonFunctions.psm1
  Libraries/TestLogs.psm1
Labels: PR-Verified, enhancement

#815 Hyperv : Fixed test cases escaped outputs
  Libraries/IntegrationServiceLibrary.psm1
  Testscripts/Windows/Migrate-VM.ps1
  Testscripts/Windows/SECUREBOOT.ps1
  Testscripts/Windows/SET-SECUREBOOT.ps1
  Testscripts/Windows/SETUP-Backup-DISK.ps1
  Testscripts/Windows/STOR-VSS-3Chain-VHD-backup.ps1
  Testscripts/Windows/STOR-VSS-BACKUP-RESTORE-DISKSTRESS.ps1
  Testscripts/Windows/STOR-VSS-BACKUP-RESTORE-PARTITION.ps1
  Testscripts/Windows/STOR-VSS-Backup-Change-Hypervvssd.ps1
  Testscripts/Windows/STOR-VSS-Backup-Disable-Enable-VSS.ps1
  Testscripts/Windows/STOR-VSS-BackupRestore-Fail.ps1
  Testscripts/Windows/STOR-VSS-BackupRestore-ISO-NoNetwork.ps1
Labels: PR-Verified, bug

#801 Added the supported distro filtering in -CustomLIS parameter
  Libraries/CommonFunctions.psm1
Labels: PR-Verified, bug, enhancement

#824 GPU-DRIVER-INSTALL: Add support for CUDA and GRID
  Libraries/TestHelpers.psm1
  Testscripts/Linux/gpu-driver-install.sh
  Testscripts/Windows/GPU-DRIVER-INSTALL.ps1
  Testscripts/Windows/NVIDIA-CUDA-DRIVER-INSTALLATION.ps1
  XML/TestCases/FunctionalTests-GPU.xml
Labels: New Testcase, PR-Verified, enhancement

#826 Fix issue when test pass and ResourceCleanup is Delete
  TestControllers/TestController.psm1
Labels: bug
