Repository LIS/LISAv2, pull requests merged in 2019-01, with the labels that each got.

#555 Remove hardcoded root Network / Perf-Network
  Libraries/CommonFunctions.psm1
  Testscripts/Linux/SR-IOV-Utils.sh
  Testscripts/Linux/enablePasswordLessRoot.sh
  Testscripts/Windows/NET-IP-Injection.ps1
  Testscripts/Windows/NET-TCP-Corruption.ps1
  Testscripts/Windows/NET-Test-Private-Network.ps1
  Testscripts/Windows/NET-Test-Vxlan.ps1
  Testscripts/Windows/NET-VLAN-Tagging.ps1
  Testscripts/Windows/NET-VLAN-Trunking.ps1
  Testscripts/Windows/SETUP-NET-Configure-Dependency-VM.ps1
  Testscripts/Windows/SETUP-PERF-Add-NIC.ps1
  Testscripts/Windows/SETUP-SR-IOV-Configure.ps1
  Testscripts/Windows/SRIOV-CHANGE-RSS.ps1
  Testscripts/Windows/SRIOV-DETACH-NIC.ps1
  Testscripts/Windows/SRIOV-DISABLE-NIC.ps1
  Testscripts/Windows/SRIOV-DISABLE-VMQ.ps1
  Testscripts/Windows/SRIOV-DISABLEVF-IPERF.ps1
  Testscripts/Windows/SRIOV-DISABLEVF-ONHOST.ps1
  Testscripts/Windows/SRIOV-DISABLEVF-PING.ps1
  Testscripts/Windows/SRIOV-MEASURE-VF-FAILBACK.ps1
  Testscripts/Windows/SRIOV-MOVE-VHD.ps1
  Testscripts/Windows/SRIOV-REBOOT-VM.ps1
  Testscripts/Windows/SRIOV-RUN-COMMON-TEST.ps1
  Testscripts/Windows/SRIOV-STRESS-SAVE-PAUSE.ps1
  Testscripts/Windows/VERIFY-ENABLE-DISABLE-SRIOV-ON-EXISTING-VM.ps1
Labels: CodeRefactoring

#569 Add ignorable boot errors and warnings for ubuntu 18.04 on Azure
  XML/Other/ignorable-boot-errors.xml
Labels: bug

#572 Fix Xfstesting-cifs and KDUMP test case issues
  Testscripts/Windows/FILE-SYSTEM-VERIFICATION-TESTS.ps1
  Testscripts/Windows/KDUMP-TestScript.ps1
Labels: bug

#579 Replace PowershellScript with testScript as init script for test cases
  Testscripts/Windows/STRESSTEST-VERIFY-RESTART.ps1
  XML/TestCases/FunctionalTests-SRIOV.xml
  XML/TestCases/StressTests.xml
Labels: bug

#578 kdump tests: fix packages definition
  Testscripts/Linux/BVT-CORE-TIMESYNC-NTP.sh
  Testscripts/Linux/KDUMP-Config.sh
Labels: bug

#577 Remove Send-CommandToVM and fix Mount-Disk function to run as sudo
  Libraries/CommonFunctions.psm1
  Testscripts/Windows/FCOPY-DISABLE-ENABLE.ps1
  Testscripts/Windows/FCOPY-LARGE-FILE.ps1
  Testscripts/Windows/FCOPY-REPEATED-DELETE.ps1
Labels: CodeRefactoring

#574 LTP: Added parameter for full/lite ltp testing
  Testscripts/Linux/Linux-Test-Project-Tests.sh
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/CommunityTests.xml
Labels: enhancement

#581 utilities: Added PS script for Hyper-V VM cleanup
  Utilities/Clean-OldHypervVMs.ps1
Labels: enhancement

#584 Fix incorrect use of check_exit_status & also a fix in bash scripts for variable assignment
  Testscripts/Linux/NET-Verify-HotAdd-MultiNIC.sh
  Testscripts/Linux/STOR_VHDXResize_GrowFSAfterResize.sh
  Testscripts/Linux/STOR_VHDXResize_PartitionDisk.sh
  Testscripts/Linux/STOR_VHDXResize_PartitionDiskOver2TB.sh
  Testscripts/Linux/STOR_VHDXResize_ReadWrite.sh
Labels: bug

#586 NTTTCP test fix (bug introduced in PR #546)
  Testscripts/Linux/perf_ntttcp.sh
Labels: bug

#596 Perf: PERF-NETWORK-UDP-THROUGHPUT-MULTICONNECTION-Synthetic/SRIOV fix
  Testscripts/Windows/PERF-NETWORK-UDP-THROUGHPUT-MULTICONNECTION-IPERF3.ps1
Labels: bug

#597 Fix DYNAMIC-MEMORY-START-HIGH-COMPETE
  XML/TestCases/FunctionalTests-DynamicMemory.xml
Labels: bug

#598 IB: Various fixes
  Testscripts/Linux/SetupRDMA.sh
  Testscripts/Linux/TestRDMA_MultiVM.sh
  Testscripts/Windows/VERIFY-INFINIBAND-MultiVM.ps1
  XML/Other/ReplaceableTestParameters.xml
Labels: CodeRefactoring, enhancement

#606 hyperv: update IP in allVmData in case it has changed after reboot
  Libraries/IntegrationServiceLibrary.psm1
  Testscripts/Windows/BVT-NET-IFUP-IFDOWN.ps1
Labels: bug

#610 Fix regresssion issue for database section name changes
  Testscripts/Windows/NESTED-HYPERV-NTTTCP-DIFFERENT-L1-NAT.ps1
  Testscripts/Windows/NESTED-HYPERV-NTTTCP-DIFFERENT-L1-PUBLIC-BRIDGE.ps1
  Testscripts/Windows/NESTED-HYPERV-STORAGE-PERF.ps1
  Testscripts/Windows/NESTED-KVM-LAGSCOPE-DIFFERENT-L1-PUBLIC-BRIDGE.ps1
  Testscripts/Windows/NESTED-KVM-NETPERF-PPS.ps1
  Testscripts/Windows/NESTED-KVM-NTTTCP-DIFFERENT-L1-PUBLIC-BRIDGE.ps1
  Testscripts/Windows/NESTED-KVM-STORAGE-PERF.ps1
  Testscripts/Windows/PERF-NETWORK-TCP-LATENCY-MULTICONNECTION-LAGSCOPE.ps1
  Testscripts/Windows/PERF-NETWORK-TCP-NETPERF.ps1
  Testscripts/Windows/PERF-NETWORK-TCP-SINGLE-CONNECTION-THROUGHPUT.ps1
  Testscripts/Windows/PERF-NETWORK-UDP-THROUGHPUT-MULTICONNECTION-IPERF3.ps1
  Testscripts/Windows/PERF-STORAGE-MULTIDISK-RAID0-FIO.ps1
  Testscripts/Windows/PERF-STORAGE-OVER-NFS.ps1
  Testscripts/Windows/PERF-SYSCALL-BENCHMARK.ps1
  Testscripts/Windows/STRESS-Web.ps1
Labels: bug

#602 lisav2: move Run-LISAv2.ps1 to a module & add unit tests
  LISAv2-Framework.psd1
  LISAv2-Framework.psm1
  Libraries/TestReport.psm1
  Run-LisaV2.ps1
  UnitTests/PowerShell/LISAv2-Framework.Tests.ps1
  azure-pipelines.yml
Labels: CodeRefactoring

#615 IB: $vmCount used to determine if setup is comple
  Testscripts/Windows/VERIFY-INFINIBAND-MultiVM.ps1
Labels: bug

#617 Fix $LASTEXITCODE is $null, and parameter issue of calling DeleteTestVMS
  Run-LisaV2.ps1
  TestControllers/TestController.psm1
Labels: bug

#616 Fix issue in collecting cases for sharing deployments
  TestControllers/TestController.psm1
Labels: bug

#565 Azure: Added STORAGE-HOT-ADD-DISK-PARALLEL Test case
  Testscripts/Windows/DiskHotAddRemove-Parallel.ps1
  XML/TestCases/FunctionalTests-Storage.xml
Labels: New Testcase

#619 framework: Wrong InternalIP in $AllVMData
  Libraries/Azure.psm1
Labels: P0, bug

#625 IB: various fixes
  Libraries/CommonFunctions.psm1
  Testscripts/Linux/TestRDMA_MultiVM.sh
  Testscripts/Windows/VERIFY-INFINIBAND-MultiVM.ps1
Labels: bug

#630 Fix lspci not installed by default in debian 9 backport
  Libraries/CommonFunctions.psm1
Labels: bug

#628 Fix test case issues for BVT category
  Libraries/CommonFunctions.psm1
  Testscripts/Linux/BVT-CORE-RELOAD-MODULES.sh
  Testscripts/Linux/BVT-CORE-TIME-CLOCKEVENT.sh
  Testscripts/Linux/BVT-CORE-TIME-CLOCKSOURCE.sh
  Testscripts/Linux/BVT-HVMODULES-CHECK.py
  Testscripts/Linux/BVT-NET-ETHTOOL-CHANGE-RINGBUFFER.sh
  Testscripts/Linux/BVT-NET-IFUP-IFDOWN.sh
  Testscripts/Linux/BVT-PASSWD-POLICY-TEST.py
  Testscripts/Linux/azuremodules.py
  Testscripts/Linux/utils.sh
Labels: enhancement

#633 IB: Various fixes #2
  Libraries/CommonFunctions.psm1
  Testscripts/Linux/TestRDMA_MultiVM.sh
Labels: RDMA, enhancement

#636 Fix STRESSTEST-CHANGE-MTU-RELOAD-NETVSC
  Libraries/IntegrationServiceLibrary.psm1
  Testscripts/Windows/STRESS-MTU-Netvsc-Reload.ps1
Labels: bug

#640 HyperV VM sizes: Updated memory/vCPU
  XML/AzureVMSizeToHyperVMapping.xml
Labels: bug

#643 azure: added HBC and HCS family support
  Libraries/Azure.psm1
Labels: P0, bug

#651 Fix LTP full test configurations on Ubuntu
  Testscripts/Linux/Linux-Test-Project-Tests.sh
  XML/TestCases/CommunityTests.xml
  XML/VMConfigurations/OneVM.xml
Labels: bug

#623 Replace deprecated ifconfig with iproute2 - ip commands
  Libraries/CommonFunctions.psm1
  Testscripts/Linux/BVT-CORE-RELOAD-MODULES.sh
  Testscripts/Linux/NET-Max-NICs.sh
  Testscripts/Linux/NET-Multicast.sh
  Testscripts/Linux/NET-Verify-HotAdd-MultiNIC.sh
  Testscripts/Linux/TestRDMA_MultiVM.sh
  Testscripts/Linux/nested_hyperv_ntttcp_different_l1_public_bridge.sh
  Testscripts/Linux/nested_kvm_lagscope_different_l1_public_bridge.sh
  Testscripts/Linux/nested_kvm_netperf_pps.sh
  Testscripts/Linux/nested_kvm_ntttcp_different_l1_nat.sh
  Testscripts/Linux/nested_kvm_ntttcp_different_l1_public_bridge.sh
  Testscripts/Linux/nested_kvm_ntttcp_private_bridge.sh
  Testscripts/Linux/nested_vm_utils.sh
  Testscripts/Linux/restart-interface-reload-netvsc.sh
  Testscripts/Linux/utils.sh
  Testscripts/Windows/NESTED-HYPERV-NTTTCP-DIFFERENT-L1-NAT.ps1
  Testscripts/Windows/STRESS-MTU-Netvsc-Reload.ps1
  Testscripts/Windows/VERIFY-INFINIBAND-MultiVM.ps1
  XML/TestCases/FunctionalTests-Network.xml
Labels: CodeRefactoring, enhancement

#650 Fix lsvmbus against ORACLE, Debian, CoreOS and ClearOS.
  Testscripts/Linux/LSVMBUS.sh
Labels: enhancement

#629 shellcheck: fix SC2006,SC2034,SC2242,SC2241,SC2239 warnings
  Testscripts/Linux/BVT-NET-IFUP-IFDOWN.sh
  Testscripts/Linux/CORE-LogCollector.sh
  Testscripts/Linux/CollectLogFile.sh
  Testscripts/Linux/ConfigureSRIOV-workaround.sh
  Testscripts/Linux/ConfigureSRIOV.sh
  Testscripts/Linux/CreateRaid.sh
  Testscripts/Linux/InstallCUDADrivers.sh
  Testscripts/Linux/LIS-Mount-FloppyDisk.sh
  Testscripts/Linux/NET-Configure-Vxlan.sh
  Testscripts/Linux/NET-Copy-Both-Ways.sh
  Testscripts/Linux/NET-Max-NICs.sh
  Testscripts/Linux/NET-Netperf-Server.sh
  Testscripts/Linux/NET-Test-Legacy.sh
  Testscripts/Linux/NET-Test-Network.sh
  Testscripts/Linux/STOR-Lis-Disk.sh
  Testscripts/Linux/STOR_VHDXResize_PartitionDisk.sh
  Testscripts/Linux/STOR_VHDXResize_PartitionDiskOver2TB.sh
  Testscripts/Linux/STOR_VSS_Disk_Stress.sh
  Testscripts/Linux/STOR_VSS_ISCSI_PartitionDisks.sh
  Testscripts/Linux/STOR_VSS_Set_VSS_Daemon.sh
  Testscripts/Linux/STOR_VSS_StopNetwork.sh
  Testscripts/Linux/Sysbench.sh
  Testscripts/Linux/TestRDMA_MultiVM.sh
  Testscripts/Linux/customKernelInstall.sh
  Testscripts/Linux/customLISInstall.sh
  Testscripts/Linux/fio_jason_parser.sh
  Testscripts/Linux/nested_hyperv_ntttcp_different_l1_nat.sh
  Testscripts/Linux/nested_hyperv_ntttcp_different_l1_public_bridge.sh
  Testscripts/Linux/nested_kvm_lagscope_different_l1_public_bridge.sh
  Testscripts/Linux/nested_kvm_netperf_pps.sh
  Testscripts/Linux/nested_kvm_netperf_pps_nat.sh
  Testscripts/Linux/nested_kvm_ntttcp_different_l1_nat.sh
  Testscripts/Linux/nested_kvm_ntttcp_different_l1_public_bridge.sh
  Testscripts/Linux/nested_kvm_ntttcp_private_bridge.sh
  Testscripts/Linux/nested_kvm_perf_fio.sh
  Testscripts/Linux/nested_kvm_storage_perf.sh
  Testscripts/Linux/nested_vm_utils.sh
  Testscripts/Linux/perf_fio.sh
  Testscripts/Linux/perf_fio_nfs.sh
  Testscripts/Linux/restart-interface-reload-netvsc.sh
  Testscripts/Linux/utils.sh
  azure-pipelines.yml
Labels: enhancement

#634 Add new test cases for netvsc ethtool options
  Testscripts/Linux/ETHTOOL-CHANGE-RINGBUFFER.sh
  Testscripts/Linux/ETHTOOL-CHECK-CHANNEL.sh
  Testscripts/Linux/ETHTOOL-CHECK-FEATURES.sh
  Testscripts/Linux/ETHTOOL-GRO-LRO.sh
  Testscripts/Linux/ETHTOOL-HANDLER-HASH-LEVELS.sh
  Testscripts/Linux/ETHTOOL-LINK-KSETTING.sh
  Testscripts/Linux/ETHTOOL-MISC-INFO.sh
  Testscripts/Linux/ETHTOOL-MSG-LEVEL.sh
  Testscripts/Linux/ETHTOOL-RSS-HASH-KEY.sh
  Testscripts/Linux/Ethtool-Check-Statistics.sh
  UnitTests/PowerShell/LISAv2-Framework.Tests.ps1
  XML/TestCases/BVT.xml
  XML/TestCases/FunctionalTests-Network.xml
Labels: New Testcase

#641 Fix functionality of Get-IPv4AndWaitForSSHStart in testcases
  Testscripts/Windows/SETUP-STOR-TakeRevert-Snapshot.ps1
  Testscripts/Windows/SRIOV-REBOOT-VM.ps1
Labels: bug

#649 Add MVAPICH MPI support in RDMA tests
  Testscripts/Linux/SetupRDMA.sh
  Testscripts/Linux/TestRDMA_MultiVM.sh
  Testscripts/Windows/VERIFY-INFINIBAND-MultiVM.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests-InfiniBand.xml
Labels: New Feature

#657 Fix VERIFY-DISK-WITH-NOBARRIER against coreos and clearos.
  LISAv2-Framework.psm1
  Testscripts/Linux/nobarrier.sh
Labels: bug

#612 LIS RPM: Add test to cross verify build version with source version
  Testscripts/Linux/LIS-VERSION-CHECK.sh
  XML/TestCases/BVT.xml
Labels: New Testcase

#660 Storage tests: fix when disk is not partitioned
  Testscripts/Windows/DiskHotAddRemove-Parallel.ps1
  Testscripts/Windows/DiskHotAddRemove-Serial.ps1
  Testscripts/Windows/VERIFY-DISK-WITH-NOBARRIER.ps1
Labels: enhancement

#639 Fix SETUP-Inject-IP-Constants.ps1 and related testcases after root removal
  Testscripts/Linux/Ethtool-Check-Statistics.sh
  Testscripts/Linux/NET-Copy-Both-Ways.sh
  Testscripts/Linux/NET-Copy-Large-File.sh
  Testscripts/Linux/NET-Jumbo-Frames.sh
  Testscripts/Linux/NET-Multicast.sh
  Testscripts/Windows/SETUP-Inject-IP-Constants.ps1
Labels: bug

#664 STRESSTEST-WEB-PARALLEL-ACCESS: Restrict test only to Ubuntu/Debian
  Testscripts/Windows/STRESS-Web.ps1
Labels: bug

#665 lisav2: hyperv: remove SourceOsVHDPath parameter
  LISAv2-Framework.psm1
  Libraries/HyperV.psm1
  README.md
  Run-LisaV2.ps1
  TestControllers/HyperVController.psm1
  XML/GlobalConfigurations.xml
  XML/TestParameters.xml
Labels: CodeRefactoring

#662 Fix issue - custom-kernel: Install fails if the VMs have a static name
  Libraries/CommonFunctions.psm1
Labels: enhancement

#672 Add support for OL
  LISAv2-Framework.psm1
  Libraries/TestHelpers.psm1
  Libraries/TestLogs.psm1
  Run-LisaV2.ps1
  TestControllers/OLController.psm1
  TestControllers/TestController.psm1
  TestProviders/OLProvider.psm1
  Testscripts/Linux/DetectLinuxDistro.sh
  Testscripts/Linux/deploy_ol_vm.sh
  XML/GlobalConfigurations.xml
  XML/TestCases/BVT.xml
Labels: New Feature

#674 Updated verification part for MVAPICH
  Testscripts/Linux/SetupRDMA.sh
Labels: bug

#682 Add TIMESYNC-BASIC on Azure
  XML/TestCases/FunctionalTests.xml
Labels: enhancement

#677 Fix issue when deploy failed against hyperv, tests still continue
  LISAv2-Framework.psm1
  Libraries/HyperV.psm1
  TestControllers/HyperVController.psm1
Labels: enhancement

#668 NVMe Direct: Add 2 new test-cases
  Testscripts/Linux/nvme_blkdiscard.sh
  Testscripts/Linux/nvme_fstrim.sh
  Testscripts/Linux/utils.sh
  XML/TestCases/FunctionalTests-NVME.xml
Labels: New Testcase
