Repository LIS/LISAv2, pull requests merged in 2019-03, with the labels that each got.

#831 Fix case BVT-CORE-RELOAD-MODULES-SMP failure
  Testscripts/Windows/BVT-CORE-RELOAD-MODULES.ps1
Labels: enhancement

#822 Fixed issue where LISAv2 was failing to cleanup resources
  Libraries/Azure.psm1
  TestControllers/TestController.psm1
  TestProviders/AzureProvider.psm1
  TestProviders/HyperVProvider.psm1
  TestProviders/OLQProvider.psm1
  TestProviders/TestProvider.psm1
  TestProviders/WSLProvider.psm1
Labels: PR-Verified, bug

#832 Support full vhd format when the VHD is in the same region as the test region
  Libraries/Azure.psm1
  Testscripts/Windows/CAPTURE-VHD-BEFORE-TEST.ps1
Labels: PR-Verified, enhancement

#827 Hyperv : Fix DM testcase issues
  Testscripts/Windows/DM-HOTADD-STRESS-APP.ps1
  Testscripts/Windows/DM-MAXMEMHONOR.ps1
  Testscripts/Windows/DM-MINMEMHONOR.ps1
  Testscripts/Windows/DM_HIGH-PRIORITY.ps1
  XML/TestCases/FunctionalTests-DynamicMemory.xml
Labels: bug

#839 Fix test case VERIFY-RESTART-INTERFACE-RELOAD-NETVSC.
  Testscripts/Linux/restart-interface-reload-netvsc.sh
Labels: bug

#841 Fix: Duplicate function Upload-TestResultToDatabase
  Libraries/Database.psm1
  TestControllers/TestController.psm1
Labels: PR-Verified

#830 Update Get-LISAv2Statistics.ps1 to support filtering by platform, tag, priority, category and area
  Utilities/Get-LISAv2Statistics.ps1
Labels: enhancement

#808 BVT-VERIFY-UUID-FSTAB: fix for SLES12
  Testscripts/Linux/BVT-VERIFY-UUID-FSTAB.py
Labels: CodeRefactoring, P1, PR-Verified, bug

#829 Add DPDK OVS functional test
  Libraries/CommonFunctions.psm1
  Testscripts/Linux/dpdk_generic_setup.sh
  Testscripts/Linux/ovs_setup.sh
  Testscripts/Windows/VERIFY-DPDK-OVS.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/FunctionalTests-DPDK.xml
Labels: DO-NOT-MERGE, P1, PR-under-test, enhancement

#776 Fixing Production Checkpoint Testcases
  Libraries/CommonFunctions.psm1
  Testscripts/Windows/PRODUCTION-CHECKPOINT-3CHAIN-VHD.ps1
  Testscripts/Windows/PRODUCTION-CHECKPOINT-PARTITION.ps1
  Testscripts/Windows/PRODUCTION-CHECKPOINT.ps1
Labels: P0, PR-under-test, bug

#843 OL: Fix for correct user in OLVM deployment
  TestProviders/OLVMProvider.psm1
Labels: bug

#838 OL: Enhancement to use template for OLVM deployment
  Libraries/Azure.psm1
Labels: enhancement

#847 SR-IOV: Disable VF on dependency VM (Hyper-V)
  Testscripts/Windows/SRIOV-DISABLEVF-IPERF.ps1
  Testscripts/Windows/SRIOV-DISABLEVF-ONHOST.ps1
  Testscripts/Windows/SRIOV-DISABLEVF-PING.ps1
Labels: enhancement

#849 dpdk_ovs: exit on failure
  Testscripts/Linux/dpdk_generic_setup.sh
  Testscripts/Linux/ovs_setup.sh
Labels: enhancement

#851 OLQ: Fixed missing parameter in DeployVM function
  TestProviders/OLQProvider.psm1
Labels: PR-Verified, bug

#842 Fix : Log files download was failing due to mismatched hostname
  Libraries/TestLogs.psm1
  Testscripts/Linux/CollectLogFile.sh
Labels: PR-Verified, bug

#833 Support 4 clients + 1 server mode for ntttcp
  Testscripts/Linux/perf_ntttcp.sh
  Testscripts/Linux/utils.sh
  Testscripts/Windows/PERF-NETWORK-THROUGHPUT-MULTICONNECTION-NTTTCP.ps1
  XML/Other/ReplaceableTestParameters.xml
  XML/TestCases/PerformanceTests.xml
  XML/VMConfigurations/MultiVMs.xml
Labels: CodeRefactoring, PR-Verified, enhancement

#846 Add secret file sample and usage.
  README.md
Labels: enhancement

#850 Fix install requirements in core functionality test scripts
  Testscripts/Linux/CORE-InitrdModulesCheck.sh
  Testscripts/Linux/LSVMBUS.sh
  Testscripts/Linux/NUMA_check.sh
  Testscripts/Linux/timesync_config.sh
  Testscripts/Linux/utils.sh
Labels: PR-Verified, enhancement
